// clikkle-app/app/docs/quick-starts/page.tsx
import Link from "next/link";

export const metadata = {
  title: "Quick starts - Docs - Appwrite",
  description:
    "Get started with your favorite framework and language in just a few clicks.",
};

type QuickStart = {
  title: string;
  href: string;
  icon: string;
};

type QuickStartCategory = {
  title: string;
  quickStarts: QuickStart[];
};

const quickStarts: QuickStartCategory[] = [
  {
    title: "Web app",
    quickStarts: [
      { title: "Next.js", href: "/docs/quick-starts/nextjs", icon: "icon-nextjs" },
      { title: "React", href: "/docs/quick-starts/react", icon: "icon-react" },
      { title: "Vue.js", href: "/docs/quick-starts/vue", icon: "web-icon-vue" },
      {
        title: "SvelteKit",
        href: "/docs/quick-starts/sveltekit",
        icon: "icon-svelte",
      },
      { title: "Angular", href: "/docs/quick-starts/angular", icon: "icon-angular" },
      { title: "Nuxt", href: "/docs/quick-starts/nuxt", icon: "web-icon-nuxt" },
      { title: "Refine", href: "/docs/quick-starts/refine", icon: "web-icon-refine" },
      { title: "Solid", href: "/docs/quick-starts/solid", icon: "icon-solidjs" },
      {
        title: "TanStack Start",
        href: "/docs/quick-starts/tanstack-start",
        icon: "web-icon-tanstack",
      },
      { title: "Web", href: "/docs/quick-starts/web", icon: "icon-js" },
    ],
  },
  {
    title: "Mobile and native",
    quickStarts: [
      { title: "Flutter", href: "/docs/quick-starts/flutter", icon: "icon-flutter" },
      {
        title: "React Native",
        href: "/docs/quick-starts/react-native",
        icon: "icon-react-native",
      },
      { title: "Android", href: "/docs/quick-starts/android", icon: "icon-android" },
      { title: "Apple", href: "/docs/quick-starts/apple", icon: "icon-apple" },
    ],
  },
  {
    title: "Server",
    quickStarts: [
      { title: "Node.js", href: "/docs/quick-starts/node", icon: "icon-node_js" },
      { title: "Python", href: "/docs/quick-starts/python", icon: "icon-python" },
      { title: ".NET", href: "/docs/quick-starts/dotnet", icon: "web-icon-dotnet" },
      { title: "PHP", href: "/docs/quick-starts/php", icon: "web-icon-php" },
      { title: "Dart", href: "/docs/quick-starts/dart", icon: "web-icon-dart" },
      { title: "Ruby", href: "/docs/quick-starts/ruby", icon: "web-icon-ruby" },
      { title: "Deno", href: "/docs/quick-starts/deno", icon: "web-icon-deno" },
      { title: "Go", href: "/docs/quick-starts/go", icon: "web-icon-go" },
      { title: "Swift", href: "/docs/quick-starts/swift", icon: "web-icon-swift" },
      { title: "Kotlin", href: "/docs/quick-starts/kotlin", icon: "web-icon-kotlin" },
    ],
  },
];

/** Appwrite `src/routes/docs/quick-starts/+page.svelte` */
export default function QuickStartsPage() {
  return (
    <main className="web-main-section" id="main">
      <article className="web-article">
        <header className="web-article-header">
          <div className="web-article-header-start flex flex-col items-start">
            <div className="relative flex items-center">
              <h1 className="text-title m-0 font-aeonik-pro font-bold text-primary">
                Quick start
              </h1>
            </div>
          </div>
          <div className="web-article-header-end" />
        </header>

        <div className="web-article-content web-u-gap-80">
        {quickStarts.map((category) => (
          <section key={category.title} className="flex flex-col gap-6">
            <h2 className="text-eyebrow font-aeonik-fono uppercase text-tertiary">
              {category.title}
            </h2>

            <ul className="web-grid-row-4 web-grid-row-4-mobile-2">
              {category.quickStarts.map((qs) => (
                <li key={qs.title} className="is-mobile-col-span-2">
                  <Link href={qs.href} className="web-card is-normal no-underline">
                    <header className="flex items-center gap-3">
                      <span className={`${qs.icon} docs-card-icon text-primary`} aria-hidden />
                      <h4 className="m-0 text-[0.875rem] font-medium leading-[1.2] text-primary">
                        {qs.title}
                      </h4>
                    </header>
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        ))}
        </div>
      </article>
    </main>
  );
}

// src/routes/docs/quick-starts/+page.svelte
<script lang="ts">
    import { MainFooter } from '$lib/components';
    import { DEFAULT_HOST } from '$lib/utils/metadata';
    import { DOCS_TITLE_SUFFIX } from '$routes/titles';

    type QuickStart = {
        title: string;
        icon: string;
        image: string;
        href: string;
    };

    type QuickStarts = Array<{
        title: string;
        quickStarts: QuickStart[];
    }>;

    const quickStarts: QuickStarts = [
        {
            title: 'Web app',
            quickStarts: [
                {
                    title: 'Next.js',
                    icon: 'icon-nextjs',
                    image: '/images/blog/placeholder.png',
                    href: 'nextjs'
                },
                {
                    title: 'React',
                    icon: 'icon-react',
                    image: '/images/blog/placeholder.png',
                    href: 'react'
                },
                {
                    title: 'Vue.js',
                    icon: 'web-icon-vue',
                    image: '/images/blog/placeholder.png',
                    href: 'vue'
                },
                {
                    title: 'SvelteKit',
                    icon: 'icon-svelte',
                    image: '/images/blog/placeholder.png',
                    href: 'sveltekit'
                },
                {
                    title: 'Angular',
                    icon: 'icon-angular',
                    image: '/images/blog/placeholder.png',
                    href: 'angular'
                },
                {
                    title: 'Nuxt',
                    icon: 'web-icon-nuxt',
                    image: '/images/blog/placeholder.png',
                    href: 'nuxt'
                },
                {
                    title: 'Refine',
                    icon: 'web-icon-refine',
                    image: '/images/blog/placeholder.png',
                    href: 'refine'
                },
                {
                    title: 'Solid',
                    icon: 'icon-solidjs',
                    image: '/images/blog/placeholder.png',
                    href: 'solid'
                },
                {
                    title: 'TanStack Start',
                    icon: 'web-icon-tanstack',
                    image: '/images/blog/placeholder.png',
                    href: 'tanstack-start'
                },
                {
                    title: 'Web',
                    icon: 'icon-js',
                    image: '/images/blog/placeholder.png',
                    href: 'web'
                }
            ]
        },
        {
            title: 'Mobile and native',
            quickStarts: [
                {
                    title: 'Flutter',
                    icon: 'icon-flutter',
                    image: '/images/blog/placeholder.png',
                    href: 'flutter'
                },
                {
                    title: 'React Native',
                    icon: 'icon-react-native',
                    image: '/images/blog/placeholder.png',
                    href: 'react-native'
                },
                {
                    title: 'Android',
                    icon: 'icon-android',
                    image: '/images/blog/placeholder.png',
                    href: 'android'
                },
                {
                    title: 'Apple',
                    icon: 'icon-apple',
                    image: '/images/blog/placeholder.png',
                    href: 'apple'
                }
            ]
        },
        {
            title: 'Server',
            quickStarts: [
                {
                    title: 'Node.js',
                    icon: 'icon-node_js',
                    image: '/images/blog/placeholder.png',
                    href: 'node'
                },
                {
                    title: 'Python',
                    icon: 'icon-python',
                    image: '/images/blog/placeholder.png',
                    href: 'python'
                },
                {
                    title: '.NET',
                    icon: 'web-icon-dotnet',
                    image: '/images/blog/placeholder.png',
                    href: 'dotnet'
                },
                {
                    title: 'PHP',
                    icon: 'web-icon-php',
                    image: '/images/blog/placeholder.png',
                    href: 'php'
                },
                {
                    title: 'Dart',
                    icon: 'web-icon-dart',
                    image: '/images/blog/placeholder.png',
                    href: 'dart'
                },
                {
                    title: 'Ruby',
                    icon: 'web-icon-ruby',
                    image: '/images/blog/placeholder.png',
                    href: 'ruby'
                },
                {
                    title: 'Deno',
                    icon: 'web-icon-deno',
                    image: '/images/blog/placeholder.png',
                    href: 'deno'
                },
                {
                    title: 'Go',
                    icon: 'web-icon-go',
                    image: '/images/blog/placeholder.png',
                    href: 'go'
                },
                {
                    title: 'Swift',
                    icon: 'web-icon-swift',
                    image: '/images/blog/placeholder.png',
                    href: 'swift'
                },
                {
                    title: 'Kotlin',
                    icon: 'web-icon-kotlin',
                    image: '/images/blog/placeholder.png',
                    href: 'kotlin'
                }
            ]
        }
    ];

    const title = 'Quick starts' + DOCS_TITLE_SUFFIX;
    const description =
        'Get started with your favorite framework and language in just a few clicks.';
    const ogImage = DEFAULT_HOST + '/images/open-graph/docs.png';
</script>

<svelte:head>
    <!-- Titles -->
    <title>{title}</title>
    <meta property="og:title" content={title} />
    <meta name="twitter:title" content={title} />
    <!-- Description -->
    <meta name="description" content={description} />
    <meta property="og:description" content={description} />
    <meta name="twitter:description" content={description} />
    <!-- Image -->
    <meta property="og:image" content={ogImage} />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:image" content={ogImage} />
    <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<main class="web-main-section" id="main">
    <article class="web-article">
        <header class="web-article-header">
            <div class="web-article-header-start web-u-cross-start flex flex-col">
                <div class="relative flex items-center">
                    <h1 class="text-title font-aeonik-pro">Quick start</h1>
                </div>
            </div>
            <div class="web-article-header-end"></div>
        </header>
        <div class="web-article-content web-u-gap-80">
            {#each quickStarts as category}
                <section class="flex flex-col gap-6">
                    <h2 class="text-eyebrow font-aeonik-fono uppercase">{category.title}</h2>
                    <ul class="web-grid-row-4 web-grid-row-4-mobile-2">
                        {#each category.quickStarts as quickStart}
                            <li class="is-mobile-col-span-2">
                                <a
                                    href={`/docs/quick-starts/${quickStart.href}`}
                                    class="web-card is-normal"
                                >
                                    <header>
                                        <span
                                            class="{quickStart.icon}"
                                            aria-hidden="true"
                                        ></span>
                                        <h4>
                                            {quickStart.title}
                                        </h4>
                                    </header>
                                </a>
                            </li>
                        {/each}
                    </ul>
                </section>
            {/each}
        </div>
    </article>
    <MainFooter variant="docs" />
</main>

<style lang="scss">
    .web-media {
        aspect-ratio: 16/9;
    }
</style>
