// src/routes/(marketing)/(components)/ai-table.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { Button } from '$lib/components/ui';
    import { VARS } from '$lib/system';

    type ModelCategory = 'Auth' | 'Databases' | 'Functions' | 'Storage' | 'Sites' | 'Messaging';

    type ArenaModel = {
        name: string;
        logo: string;
        colorLogo: string;
        cost: string; // The API provides cost fields, but format it appropriately
        overall: number;
        categories: Record<ModelCategory, number>;
    };

    let models = $state<ArenaModel[]>([]);
    let categoryKeys = $state<ModelCategory[]>([
        'Auth',
        'Databases',
        'Functions',
        'Storage',
        'Sites',
        'Messaging'
    ]);

    const logoMap: Record<string, { dark: string; color: string }> = {
        OpenAI: {
            dark: '/images/docs/mcp/logos/dark/openai.svg',
            color: '/images/docs/mcp/logos/color/openai.svg'
        },
        Anthropic: {
            dark: '/images/docs/mcp/logos/dark/claude.svg',
            color: '/images/docs/mcp/logos/color/claude.svg'
        },
        MoonshotAI: {
            dark: '/images/docs/mcp/logos/dark/kimi.svg',
            color: '/images/docs/mcp/logos/color/kimi.svg'
        },
        Google: {
            dark: '/images/docs/mcp/logos/dark/gemini.svg',
            color: '/images/docs/mcp/logos/color/gemini.svg'
        }
    };

    onMount(async () => {
        try {
            const res = await fetch('/api/arena');
            const data = await res.json();

            // Map the parsed AI data to match the component's internal structure
            models = (data?.models || []).slice(0, 4).map((m: any) => ({
                name: m.modelName,
                logo: logoMap[m.provider]?.dark || '/images/docs/mcp/logos/dark/openai.svg', // Fallback icon
                colorLogo: logoMap[m.provider]?.color || '/images/docs/mcp/logos/color/openai.svg',
                cost: `$${(m.promptCostPerMillionTokens || 0).toFixed(2)}`,
                overall: m.overall,
                categories: {
                    Auth: m.scores?.auth ?? 0,
                    Databases: m.scores?.databases ?? 0,
                    Functions: m.scores?.functions ?? 0,
                    Storage: m.scores?.storage ?? 0,
                    Sites: m.scores?.sites ?? 0,
                    Messaging: m.scores?.messaging ?? 0
                }
            }));

            // Re-initialize animated scores once models are loaded dynamically
            animatedScores = models.map(() => START_VALUE);
            hasAnimated = false; // Reset so sequence animates once new data loads

            // Trigger animation if in view
            if (scoreSection) {
                const rect = scoreSection.getBoundingClientRect();
                if (rect.top < window.innerHeight && rect.bottom >= 0) {
                    animateScores();
                }
            }
        } catch (e) {
            console.error('Failed to load arena data:', e);
        }
    });

    // Score count-up animation
    const START_VALUE = 90;
    let scoreSection: HTMLElement;
    let hasAnimated = $state(false);
    let animatedScores = $state<number[]>([]);

    function easeOutCubic(t: number): number {
        return 1 - Math.pow(1 - t, 3);
    }

    type ScoreTier = 'high' | 'mid' | 'low';

    const SCORE_THRESHOLD_HIGH = 85;
    const SCORE_THRESHOLD_LOW = 50;

    function getScoreTier(score: number): ScoreTier {
        if (score >= SCORE_THRESHOLD_HIGH) return 'high';
        if (score >= SCORE_THRESHOLD_LOW) return 'mid';
        return 'low';
    }

    function getScoreColor(score: number): string {
        const tier = getScoreTier(score);
        if (tier === 'low') return '#FF453A';
        if (tier === 'mid') return '#FE9567';
        return '#85DBD8';
    }

    function getScoreClass(score: number): string {
        return `score-${getScoreTier(score)}`;
    }

    function getOverallColor(score: number): string {
        const tier = getScoreTier(score);
        if (tier === 'high') return '#85DBD8';
        if (tier === 'mid') return '#FE9567';
        return '#FF453A';
    }

    function animateScores() {
        if (hasAnimated) return;
        hasAnimated = true;

        const targets = models.map((m) => m.overall);
        const duration = 1000;
        const stagger = 100;

        models.forEach((_, i) => {
            const delay = i * stagger;
            const start = performance.now() + delay;

            function tick(now: number) {
                const elapsed = now - start;
                if (elapsed < 0) {
                    requestAnimationFrame(tick);
                    return;
                }
                const progress = Math.min(elapsed / duration, 1);
                const eased = easeOutCubic(progress);
                animatedScores[i] = START_VALUE + (targets[i] - START_VALUE) * eased;

                if (progress < 1) {
                    requestAnimationFrame(tick);
                }
            }

            requestAnimationFrame(tick);
        });
    }

    $effect(() => {
        if (!scoreSection) return;
        const observer = new IntersectionObserver(
            (entries) => {
                if (entries[0].isIntersecting) {
                    animateScores();
                    observer.disconnect();
                }
            },
            { threshold: 0.2 }
        );
        observer.observe(scoreSection);
        return () => observer.disconnect();
    });
</script>

<!-- Agent Skill + LLM Compatibility -->
<div
    class="container pt-14 md:pt-20 clikkle-brand-scope"
>
    <!-- Pitch -->
    <div
        class="mb-8 flex flex-col items-start gap-6 sm:flex-row sm:items-center sm:justify-between"
    >
        <h3 class="font-aeonik-pro text-label text-primary mb-0 max-w-[480px]">
            Works with every major LLM.
            <span class="text-secondary"
                >Find out how well your model integrates with Appwrite.</span
            >
        </h3>
        <div class="flex w-full flex-col gap-3 sm:w-auto sm:flex-row sm:items-center sm:gap-4">
            <Button
                href="/docs/tooling/skills"
                target="_blank"
                rel="noopener noreferrer"
                class="is-full-width-mobile">Install skill</Button
            >
            <Button
                variant="secondary"
                href={VARS.ARENA_ENDPOINT}
                target="_blank"
                rel="noopener noreferrer"
                class="is-full-width-mobile">View full benchmark</Button
            >
        </div>
    </div>

    <!-- Benchmark table -->
    <div class="border-smooth overflow-x-auto border border-dashed" bind:this={scoreSection}>
        <table class="w-full">
            <thead>
                <tr class="border-smooth border-b border-dashed bg-[#232325]">
                    <td
                        class="min-w-[140px] shrink-0 px-4 py-3 text-left text-xs text-white/50 sm:px-5"
                        >Model</td
                    >
                    <td class="hidden px-5 py-3 text-left text-xs text-white/50 sm:table-cell"
                        >Cost/1M</td
                    >
                    <td class="px-4 py-3 text-right text-xs text-white/50 sm:px-5 sm:text-left"
                        >Overall</td
                    >
                    {#each categoryKeys as cat}
                        <td class="hidden px-5 py-3 text-center text-xs text-white/50 md:table-cell"
                            >{cat}</td
                        >
                    {/each}
                </tr>
            </thead>
            <tbody>
                {#each models as model, i (model.name)}
                    {@const isLast = i === models.length - 1}
                    <tr class="group border-smooth {!isLast ? 'border-b border-dashed' : ''}">
                        <td class="min-w-[140px] shrink-0 px-4 py-3 sm:px-5">
                            <div class="flex min-w-0 items-center gap-3">
                                <img
                                    src={model.colorLogo}
                                    alt=""
                                    class="h-5 w-5 shrink-0 opacity-60 grayscale transition-all duration-300 group-hover:opacity-100 group-hover:grayscale-0"
                                />
                                <span
                                    class="text-primary text-sm font-medium whitespace-nowrap sm:text-base"
                                    >{model.name}</span
                                >
                            </div>
                        </td>
                        <td class="hidden px-5 py-3 text-base text-white/40 sm:table-cell"
                            >{model.cost}</td
                        >
                        <td class="px-4 py-3 text-right sm:px-5 sm:text-left">
                            <span
                                class="font-aeonik-pro text-lg font-medium"
                                style="color: {getOverallColor(animatedScores[i])}"
                                >{animatedScores[i].toFixed(1)}<span class="text-sm">%</span></span
                            >
                        </td>
                        {#each categoryKeys as cat}
                            <td class="hidden px-5 py-3 text-center md:table-cell">
                                <span
                                    class="text-sm text-white/60 transition-colors duration-300 group-hover:text-[color:var(--hover-color)]"
                                    style="--hover-color: {getScoreColor(model.categories[cat])};"
                                    >{model.categories[cat]}%</span
                                >
                            </td>
                        {/each}
                    </tr>
                {/each}
            </tbody>
        </table>
    </div>
</div>

<style>
    /*
     * Force a 1:1 Appwrite button clone in this section only,
     * but using Clikkle blue (no pink anywhere).
     */
    .clikkle-brand-scope {
        --clikkle-brand-primary: #2d63ff;
        --clikkle-brand-secondary: #1e3a8a;
    }

    .clikkle-brand-scope :global(.web-button) {
        --m-border-radius: var(--border-radius-small, 8px);
        --m-border-size: 1px;

        box-sizing: border-box;
        min-block-size: 40px;
        padding-block: 7px;
        padding-inline: 14px;
        border-radius: var(--m-border-radius);
        font-size: 14px;
        font-weight: 500;
        line-height: 1;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: 8px;
        transition: var(--transition);
        text-decoration: none !important;
        cursor: pointer;
        border: solid var(--m-border-size) transparent;
        font-family: inherit;
        white-space: pre;
        user-select: none;

        background: linear-gradient(
            135deg,
            var(--clikkle-brand-primary) 0%,
            var(--clikkle-brand-primary) 61%,
            var(--clikkle-brand-secondary) 100%
        );
        background-origin: border-box;
        color: #fff;
    }

    .clikkle-brand-scope :global(.web-button:hover:not(:disabled)) {
        box-shadow: 0 0 32px 0 color-mix(in srgb, var(--clikkle-brand-primary) 32%, transparent);
    }

    .clikkle-brand-scope :global(.web-button:active:not(:disabled)) {
        box-shadow: 0 0 32px 0 color-mix(in srgb, var(--clikkle-brand-primary) 24%, transparent);
    }

    .clikkle-brand-scope :global(.web-button:focus-visible:not(:disabled)) {
        box-shadow: 0 0 0 4px color-mix(in srgb, var(--clikkle-brand-primary) 24%, transparent);
        outline: none;
    }

    :global(html.dark) .clikkle-brand-scope :global(.web-button:focus-visible:not(:disabled)) {
        box-shadow: 0 0 0 4px color-mix(in srgb, var(--clikkle-brand-primary) 48%, transparent);
    }

    /*
     * Secondary variant: drive Appwrite’s existing `border-gradient` mixin by setting
     * `--m-border-gradient-before/after` exactly like Appwrite does, but in Clikkle blue.
     */
    .clikkle-brand-scope :global(.web-button.is-secondary) {
        background-image: none !important;
        border-width: 0 !important;
        color: rgba(255, 255, 255, 0.92) !important;
        background: rgba(45, 99, 255, 0.04) !important;
        box-shadow: 0px -6px 10px 0px rgba(45, 99, 255, 0.08) inset !important;

        --m-border-gradient-before: linear-gradient(
            to bottom,
            rgba(45, 99, 255, 0.48) 0%,
            rgba(45, 99, 255, 0) 180%
        );
        --m-border-gradient-after: radial-gradient(
            42.86% 42.86% at 50.55% -0%,
            rgba(255, 255, 255, 0.2) 0%,
            rgba(255, 255, 255, 0) 100%
        );
    }

    .clikkle-brand-scope :global(.web-button.is-secondary:hover:not(:disabled)) {
        background: rgba(45, 99, 255, 0.10) !important;
        box-shadow: 0px -6px 10px 0px rgba(45, 99, 255, 0.08) inset !important;
        --m-border-gradient-before: linear-gradient(
            180deg,
            rgba(45, 99, 255, 0.64) 0%,
            rgba(45, 99, 255, 0) 163.1%
        );
        --m-border-gradient-after: radial-gradient(
            42.86% 42.86% at 50.55% 0%,
            rgba(255, 255, 255, 0.20) 0%,
            rgba(255, 255, 255, 0.00) 100%
        );
    }

    .clikkle-brand-scope :global(.web-button.is-secondary:active:not(:disabled)) {
        background: rgba(45, 99, 255, 0.16) !important;
        box-shadow: 0px -6px 10px 0px rgba(45, 99, 255, 0.08) inset !important;
        --m-border-gradient-before: linear-gradient(
            180deg,
            rgba(45, 99, 255, 0.64) 0%,
            rgba(45, 99, 255, 0) 163.1%
        );
        --m-border-gradient-after: radial-gradient(
            42.86% 42.86% at 50.55% 0%,
            rgba(255, 255, 255, 0.32) 0%,
            rgba(255, 255, 255, 0.00) 100%
        );
    }

    .clikkle-brand-scope :global(.web-button.is-secondary:focus-visible:not(:disabled)) {
        background: rgba(45, 99, 255, 0.04) !important;
        box-shadow:
            0px 0px 0px 4px rgba(45, 99, 255, 0.16),
            0px -6px 10px 0px rgba(45, 99, 255, 0.08) inset !important;
    }
</style>

// clikkle-app/components/ai-table.tsx
"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Link from "next/link";

type ModelCategory = "Auth" | "Databases" | "Functions" | "Storage" | "Sites" | "Messaging";

type ArenaModel = {
  name: string;
  logo: string;
  colorLogo: string;
  cost: string;
  overall: number;
  categories: Record<ModelCategory, number>;
};

const categoryKeys: ModelCategory[] = [
  "Auth",
  "Databases",
  "Functions",
  "Storage",
  "Sites",
  "Messaging",
];

const models: ArenaModel[] = [
  {
    name: "GPT-4.1",
    logo: "/clikkle/images/docs/mcp/logos/dark/openai.svg",
    colorLogo: "/clikkle/images/docs/mcp/logos/color/openai.svg",
    cost: "$2.00",
    overall: 97.4,
    categories: { Auth: 99, Databases: 98, Functions: 97, Storage: 96, Sites: 97, Messaging: 95 },
  },
  {
    name: "Claude 4 Sonnet",
    logo: "/clikkle/images/docs/mcp/logos/dark/claude.svg",
    colorLogo: "/clikkle/images/docs/mcp/logos/color/claude.svg",
    cost: "$3.00",
    overall: 96.7,
    categories: { Auth: 98, Databases: 97, Functions: 96, Storage: 95, Sites: 97, Messaging: 96 },
  },
  {
    name: "Kimi K2",
    logo: "/clikkle/images/docs/mcp/logos/dark/kimi.svg",
    colorLogo: "/clikkle/images/docs/mcp/logos/color/kimi.svg",
    cost: "$0.14",
    overall: 94.3,
    categories: { Auth: 96, Databases: 95, Functions: 93, Storage: 94, Sites: 92, Messaging: 91 },
  },
  {
    name: "Gemini 2.5 Pro",
    logo: "/clikkle/images/docs/mcp/logos/dark/gemini.svg",
    colorLogo: "/clikkle/images/docs/mcp/logos/color/gemini.svg",
    cost: "$1.25",
    overall: 95.1,
    categories: { Auth: 97, Databases: 96, Functions: 94, Storage: 95, Sites: 94, Messaging: 93 },
  },
];

const START_VALUE = 90;
const SCORE_THRESHOLD_HIGH = 85;
const SCORE_THRESHOLD_LOW = 50;

function getScoreColor(score: number): string {
  if (score >= SCORE_THRESHOLD_HIGH) return "#85DBD8";
  if (score >= SCORE_THRESHOLD_LOW) return "#FE9567";
  return "#FF453A";
}

function getOverallColor(score: number): string {
  if (score >= SCORE_THRESHOLD_HIGH) return "#85DBD8";
  if (score >= SCORE_THRESHOLD_LOW) return "#FE9567";
  return "#FF453A";
}

function easeOutCubic(t: number): number {
  return 1 - Math.pow(1 - t, 3);
}

export function AiTable() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [animatedScores, setAnimatedScores] = useState<number[]>(
    models.map(() => START_VALUE)
  );
  const hasAnimatedRef = useRef(false);

  const animateScores = useCallback(() => {
    if (hasAnimatedRef.current) return;
    hasAnimatedRef.current = true;

    const targets = models.map((m) => m.overall);
    const duration = 1000;
    const stagger = 100;

    models.forEach((_, i) => {
      const delay = i * stagger;
      const start = performance.now() + delay;

      function tick(now: number) {
        const elapsed = now - start;
        if (elapsed < 0) {
          requestAnimationFrame(tick);
          return;
        }
        const progress = Math.min(elapsed / duration, 1);
        const eased = easeOutCubic(progress);
        const value = START_VALUE + (targets[i] - START_VALUE) * eased;

        setAnimatedScores((prev) => {
          const next = [...prev];
          next[i] = value;
          return next;
        });

        if (progress < 1) {
          requestAnimationFrame(tick);
        }
      }

      requestAnimationFrame(tick);
    });
  }, []);

  useEffect(() => {
    const el = sectionRef.current;
    if (!el) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          animateScores();
          observer.disconnect();
        }
      },
      { threshold: 0.2 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [animateScores]);

  return (
    <div className="container pt-14 md:pt-20">
      {/* Pitch */}
      <div className="mb-8 flex flex-col items-start gap-6 sm:flex-row sm:items-center sm:justify-between">
        <h3 className="font-aeonik-pro text-label text-primary mb-0 max-w-[480px]">
          Works with every major LLM.{" "}
          <span className="text-secondary">
            Find out how well your model integrates with Clikkle.
          </span>
        </h3>
        <div className="not-prose flex w-full flex-col gap-3 sm:w-auto sm:flex-row sm:items-center sm:gap-4">
          <Link
            href="/docs/tooling/skills"
            target="_blank"
            rel="noopener noreferrer"
            className="web-btn web-btn--appwrite-primary w-full justify-center sm:w-auto"
          >
            Install skill
          </Link>
          <a
            href="https://arena.clikkle.com"
            target="_blank"
            rel="noopener noreferrer"
            className="web-btn web-btn--appwrite-secondary w-full justify-center sm:w-auto"
          >
            View full benchmark
          </a>
        </div>
      </div>

      {/* Benchmark table */}
      <div
        className="border-smooth overflow-x-auto border border-dashed"
        ref={sectionRef}
      >
        <table className="w-full">
          <thead>
            <tr className="border-smooth border-b border-dashed bg-[#232325]">
              <td className="min-w-[140px] shrink-0 px-4 py-3 text-left text-xs text-white/50 sm:px-5">
                Model
              </td>
              <td className="hidden px-5 py-3 text-left text-xs text-white/50 sm:table-cell">
                Cost/1M
              </td>
              <td className="px-4 py-3 text-right text-xs text-white/50 sm:px-5 sm:text-left">
                Overall
              </td>
              {categoryKeys.map((cat) => (
                <td
                  key={cat}
                  className="hidden px-5 py-3 text-center text-xs text-white/50 md:table-cell"
                >
                  {cat}
                </td>
              ))}
            </tr>
          </thead>
          <tbody>
            {models.map((model, i) => {
              const isLast = i === models.length - 1;
              return (
                <tr
                  key={model.name}
                  className={`group border-smooth ${
                    !isLast ? "border-b border-dashed" : ""
                  }`}
                >
                  <td className="min-w-[140px] shrink-0 px-4 py-3 sm:px-5">
                    <div className="flex min-w-0 items-center gap-3">
                      <img src={model.colorLogo}
                        alt=""
                        width={20}
                        height={20}
                        className="h-5 w-5 shrink-0 opacity-60 grayscale transition-all duration-300 group-hover:opacity-100 group-hover:grayscale-0" loading="lazy" />
                      <span className="text-primary text-sm font-medium whitespace-nowrap sm:text-base">
                        {model.name}
                      </span>
                    </div>
                  </td>
                  <td className="hidden px-5 py-3 text-base text-white/40 sm:table-cell">
                    {model.cost}
                  </td>
                  <td className="px-4 py-3 text-right sm:px-5 sm:text-left">
                    <span
                      className="font-aeonik-pro text-lg font-medium"
                      style={{ color: getOverallColor(animatedScores[i]) }}
                    >
                      {animatedScores[i].toFixed(1)}
                      <span className="text-sm">%</span>
                    </span>
                  </td>
                  {categoryKeys.map((cat) => (
                    <td
                      key={cat}
                      className="hidden px-5 py-3 text-center md:table-cell"
                    >
                      <span
                        className="text-sm text-white/60 transition-colors duration-300 group-hover:text-[color:var(--hover-color)]"
                        style={
                          {
                            "--hover-color": getScoreColor(
                              model.categories[cat]
                            ),
                          } as React.CSSProperties
                        }
                      >
                        {model.categories[cat]}%
                      </span>
                    </td>
                  ))}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
