// src/lib/components/marketing/pullquote.svelte
<script lang="ts">
    import { cn } from '$lib/utils/cn';
    import type { SvelteHTMLElements } from 'svelte/elements';

    type BlockquoteElementProps = SvelteHTMLElements['blockquote'];

    interface PullquoteProps extends BlockquoteElementProps {
        name: string;
        title: string;
        avatar: string;
    }

    const { class: className, children, title, avatar, name }: PullquoteProps = $props();
</script>

<div class="container mx-auto">
    <blockquote
        class={cn(
            className,
            'font-aeonik-pro mx-auto flex w-full max-w-[40rem] flex-col items-center justify-center gap-4 py-10 pb-20 text-center md:py-16'
        )}
    >
        <h2 class="text-subtitle text-primary font-medium md:text-[1.375rem] md:leading-snug">
            <span class="text-accent -mr-1">“</span>
            {@render children?.()}
            <span class="text-accent -ml-1">”</span>
        </h2>
        <div class="flex items-center gap-2">
            <img src={avatar} alt={name} class="size-6 rounded-full" />
            <h5 class="text-caption text-primary font-medium">
                {name}, <span class="text-secondary">{title}</span>
            </h5>
        </div>
    </blockquote>
</div>

// components/pullquote.tsx
"use client";

import { cn } from "@/lib/utils";

interface PullquoteProps {
  name: string;
  title: string;
  avatar: string;
  children: React.ReactNode;
  className?: string;
}

export function Pullquote({ name, title: jobTitle, avatar, children, className }: PullquoteProps) {
  return (
    <section className={cn("container py-20", className)}>
      <figure className="mx-auto flex max-w-3xl flex-col items-center gap-8 text-center">
        <blockquote>
          <p className="font-aeonik-pro text-subtitle text-primary text-pretty leading-relaxed">
            &ldquo;{children}&rdquo;
          </p>
        </blockquote>
        <figcaption className="flex items-center gap-3">
          <img
            loading="lazy"
            src={avatar}
            alt={name}
            className="size-12 rounded-full object-cover"
          />
          <div className="text-left">
            <cite className="text-caption text-primary not-italic font-medium">{name}</cite>
            <p className="text-caption text-secondary">{jobTitle}</p>
          </div>
        </figcaption>
      </figure>
    </section>
  );
}
