// app/docs/tutorials/page.tsx
import Link from "next/link";
import fs from "fs";
import path from "path";

export const metadata = {
  title: "Tutorials - Docs - Clikkle",
  description:
    "Follow a simple tutorial to get started with Clikkle in your preferred framework quickly and easily.",
};

type Tutorial = {
  title: string;
  framework: string;
  href: string;
};

type TutorialCategory = {
  title: string;
  tutorials: Tutorial[];
};

function getTutorials(): TutorialCategory[] {
  // Scan the content/docs/tutorials directory for available tutorials
  const tutorialsDir = path.join(process.cwd(), "content/docs/tutorials");
  const entries: string[] = [];

  if (fs.existsSync(tutorialsDir)) {
    const items = fs.readdirSync(tutorialsDir);
    for (const item of items) {
      const fullPath = path.join(tutorialsDir, item);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        entries.push(item);
      } else if (item.endsWith(".markdoc")) {
        entries.push(item.replace(".markdoc", ""));
      }
    }
  }

  const frameworkMap: Record<string, { title: string; category: string }> = {
    react: { title: "Build a ideas tracker with React", category: "Web" },
    "react-native": { title: "Build a ideas tracker with React Native", category: "Mobile" },
    nextjs: { title: "Build a ideas tracker with Next.js", category: "Web" },
    "nextjs-ssr-auth": { title: "SSR auth with Next.js", category: "Web" },
    vue: { title: "Build a ideas tracker with Vue.js", category: "Web" },
    angular: { title: "Build a ideas tracker with Angular", category: "Web" },
    sveltekit: { title: "Build a ideas tracker with SvelteKit", category: "Web" },
    "sveltekit-ssr-auth": { title: "SSR auth with SvelteKit", category: "Web" },
    nuxt: { title: "Build a ideas tracker with Nuxt", category: "Web" },
    "nuxt-ssr-auth": { title: "SSR auth with Nuxt", category: "Web" },
    astro: { title: "Build a ideas tracker with Astro", category: "Web" },
    "astro-ssr-auth": { title: "SSR auth with Astro", category: "Web" },
    flutter: { title: "Build a ideas tracker with Flutter", category: "Mobile" },
    android: { title: "Build a ideas tracker with Android", category: "Mobile" },
    apple: { title: "Build a ideas tracker with Apple", category: "Mobile" },
    refine: { title: "Build a ideas tracker with Refine", category: "Web" },
  };

  const categories: Record<string, Tutorial[]> = {};

  for (const entry of entries) {
    const info = frameworkMap[entry] || {
      title: `Tutorial: ${entry}`,
      category: "Other",
    };
    if (!categories[info.category]) categories[info.category] = [];
    categories[info.category].push({
      title: info.title,
      framework: entry
        .replace(/-/g, " ")
        .replace(/\b\w/g, (l) => l.toUpperCase())
        .replace("Ssr", "SSR")
        .replace("Nextjs", "Next.js")
        .replace("Sveltekit", "SvelteKit")
        .replace("React Native", "React Native"),
      href: `/docs/tutorials/${entry}`,
    });
  }

  return Object.entries(categories).map(([title, tutorials]) => ({
    title,
    tutorials,
  }));
}

export default function TutorialsPage() {
  const tutorials = getTutorials();

  return (
    <div className="flex-1 min-w-0 max-w-[800px] pt-12 pb-24 px-6 md:px-10 lg:pl-[4rem]">
      <h1 className="text-4xl font-aeonik-pro font-bold tracking-tight text-white mb-12">
        Tutorials
      </h1>

      <div className="flex flex-col gap-16">
        {tutorials.map((category) => (
          <section key={category.title} className="flex flex-col gap-6">
            <h2 className="text-[11px] font-bold uppercase tracking-wider text-white/40">
              {category.title}
            </h2>
            <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              {category.tutorials.map((tutorial) => (
                <li key={tutorial.href}>
                  <Link
                    href={tutorial.href}
                    className="group flex flex-col gap-2 rounded-xl border border-white/5 bg-white/[0.02] px-4 py-3 transition-all hover:bg-white/[0.05] hover:border-white/10"
                  >
                    <h3 className="text-sm font-medium text-white group-hover:text-[#2D63FF] transition-colors">
                      {tutorial.framework}
                    </h3>
                    <p className="text-xs text-white/40 line-clamp-2">
                      {tutorial.title}
                    </p>
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>
    </div>
  );
}

// src/routes/docs/tutorials/+page.svelte
<script lang="ts">
    import { MainFooter } from '$lib/components';
    import { DEFAULT_HOST } from '$lib/utils/metadata';
    import { DOCS_TITLE_SUFFIX } from '$routes/titles';

    const title = 'Tutorials' + DOCS_TITLE_SUFFIX;
    const description =
        'Follow a simple tutorial to get started with Appwrite in your preferred framework quickly and easily.';
    const ogImage = DEFAULT_HOST + '/images/open-graph/docs.png';

    let { data } = $props();

    type MappedTutorial = (typeof data.tutorials)[number]['tutorials'][number];

    const iconMap: Record<string, string> = {
        'react native': 'icon-react-native',
        react: 'icon-react',
        vue: 'web-icon-vue',
        angular: 'icon-angular',
        svelte: 'icon-svelte',
        sveltekit: 'icon-svelte',
        'sveltekit ssr': 'icon-svelte',
        android: 'icon-android',
        apple: 'icon-apple',
        flutter: 'icon-flutter',
        nuxt: 'icon-nuxt',
        'nuxt ssr': 'icon-nuxt',
        stripe: 'icon-stripe',
        refine: 'web-icon-refine',
        'next.js': 'icon-nextjs',
        'next.js ssr': 'icon-nextjs',
        astro: 'icon-astro',
        'astro ssr': 'icon-astro'
    };

    const getIcon = (tutorial: MappedTutorial) => {
        if (!tutorial.framework) return ''; // TODO: Default icon
        return iconMap[tutorial.framework.toLowerCase()];
    };
</script>

<svelte:head>
    <!-- Titles -->
    <title>{title}</title>
    <meta property="og:title" content={title} />
    <meta name="twitter:title" content={title} />
    <!-- Description -->
    <meta name="description" content={description} />
    <meta property="og:description" content={description} />
    <meta name="twitter:description" content={description} />
    <!-- Image -->
    <meta property="og:image" content={ogImage} />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:image" content={ogImage} />
    <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<main class="web-main-section" id="main">
    <article class="web-article">
        <header class="web-article-header">
            <div class="web-article-header-start web-u-cross-start flex flex-col">
                <div class="relative flex items-center">
                    <h1 class="text-title font-aeonik-pro">Tutorials</h1>
                </div>
            </div>
            <div class="web-article-header-end"></div>
        </header>
        <div class="web-article-content web-u-gap-80">
            {#each data.tutorials as category}
                <section class="flex flex-col gap-6">
                    <h2 class="text-eyebrow uppercase">{category.title}</h2>
                    <ul class="web-grid-row-4 web-grid-row-4-mobile-1">
                        {#each category.tutorials as tutorial}
                            <li>
                                {#if tutorial.draft === true}
                                    <a
                                        href={tutorial.href}
                                        class="web-card is-normal draft"
                                        aria-disabled="true"
                                        tabindex="-1"
                                    >
                                        <header>
                                            <span
                                                class="{getIcon(tutorial)}"
                                                aria-hidden="true"
                                            ></span>
                                            <h3>
                                                {tutorial.framework}
                                            </h3>
                                            <span class="badge text-caption">Coming Soon</span>
                                        </header>
                                    </a>
                                {:else}
                                    <a href={tutorial.href} class="web-card is-normal">
                                        <header>
                                            <span
                                                class="{getIcon(tutorial)}"
                                                aria-hidden="true"
                                            ></span>
                                            <h3>
                                                {tutorial.framework}
                                            </h3>
                                        </header>
                                        <p class="text-sub-body mt-1">
                                            {tutorial.title}
                                        </p>
                                    </a>
                                {/if}
                            </li>
                        {/each}
                    </ul>
                </section>
            {/each}
        </div>
    </article>

    <MainFooter variant="docs" />
</main>

<style lang="scss">
    .badge {
        border-radius: 0.25rem;
        background: rgba(253, 54, 110, 0.24);
        padding: 0.0625rem 0.375rem;
        margin-inline-start: 0.25rem;
    }

    .draft {
        opacity: 0.4;
        pointer-events: none;
    }
</style>
