// src/routes/pricing/+page.svelte
<script lang="ts">
    import { FooterNav, MainFooter, PreFooter } from '$lib/components';
    import { DEFAULT_HOST } from '$lib/utils/metadata';

    import { Main } from '$lib/layouts';
    import { TITLE_SUFFIX } from '$routes/titles';
    import ComparePlans from './compare-plans.svelte';
    import Faq from './faq.svelte';
    import BG from './bg.png';
    import { getAppwriteDashboardUrl } from '$lib/utils/dashboard';
    import { Button, BadgeTransparent, Icon } from '$lib/components/ui';
    import { SHOW_SCALE_PLAN } from '$lib/constants/feature-flags';

    const title = 'Pricing' + TITLE_SUFFIX;
    const description = 'Explore our straightforward pricing plans that scale with your project.';
    const ogImage = DEFAULT_HOST + '/images/open-graph/website.png';
</script>

<svelte:head>
    <!-- Titles -->
    <title>{title}</title>
    <meta property="og:title" content={title} />
    <meta name="twitter:title" content={title} />
    <!-- Description -->
    <meta name="description" content={description} />
    <meta property="og:description" content={description} />
    <meta name="twitter:description" content={description} />
    <!-- Image -->
    <meta property="og:image" content={ogImage} />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:image" content={ogImage} />
    <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<div
    class="web-location-for-mobile absolute overflow-hidden"
    style:pointer-events="none"
    style:inline-size="100%"
>
    <img
        src={BG}
        alt=""
        style="margin-inline:auto; display:block; width: 1369px; height: auto;"
    />
</div>

<Main>
    <div class="web-big-padding-section mt-2">
        <div class="dark pt-8">
            <div class="web-big-padding-section-level-2">
                <section class="container">
                    <div class="web-hero">
                        <h1
                            class="text-display font-aeonik-pro web-u-max-width-900 web-u-opacity-90 web-u-mobile-align-text-center self-center"
                            style="background: linear-gradient(90deg, #F47298 0%, #E4E1E5 61.98%, #E4E4E7 100%);
                                -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; padding-block-end:2px;"
                        >
                            Pricing
                        </h1>
                        <p
                            class="text-description max-w-sm self-center text-center opacity-90"
                            style="background: linear-gradient(90deg, #F47298 0%, #E4E1E5 61.98%, #E4E4E7 100%);
                                -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; padding-block-end:2px;"
                        >
                            Appwrite offers simple and transparent pricing plans with no surprises.
                        </p>
                    </div>
                </section>
            </div>
            <div class="web-big-padding-section-level-2">
                <section class="container">
                    <div
                        class="web-pricing-cards"
                        style:--columns-template={SHOW_SCALE_PLAN
                            ? 'repeat(4, 1fr)'
                            : 'repeat(3, 1fr)'}
                    >
                        <ul class="web-pricing-cards-list">
                            <li>
                                <article
                                    class="web-card is-transparent has-border-gradient h-full"
                                    style="background: linear-gradient(180deg, rgba(255, 255, 255, 0.04) 63.19%, rgba(255, 255, 255, 0.00) 100%);"
                                >
                                    <div class="web-pricing-cards-item">
                                        <header class="web-pricing-cards-header">
                                            <h2
                                                id="starter"
                                                class="text-label text-primary font-aeonik-pro"
                                            >
                                                Free
                                            </h2>
                                            <div
                                                class="text-title font-aeonik-pro text-primary mt-12 -mb-6"
                                            >
                                                $0
                                            </div>
                                            <div class="mt-1">&nbsp;</div>
                                            <p class="text-main-body mt-4 h-[5rem] font-medium">
                                                A great fit for passion projects and small
                                                applications.
                                            </p>
                                            <Button
                                                variant="secondary"
                                                class="is-full-width mt-8"
                                                href={getAppwriteDashboardUrl('/register')}
                                                event="pricing-cards-free-click"
                                            >
                                                <span class="text-sub-body font-medium"
                                                    >Start building</span
                                                >
                                            </Button>
                                        </header>
                                        <div class="web-pricing-cards-content">
                                            <ul class="web-checked-list-circle">
                                                <li><span>5GB bandwidth</span></li>
                                                <li><span>2GB storage</span></li>
                                                <li><span>750K executions</span></li>
                                                <li><span>75K monthly active users</span></li>
                                                <li><span>Community support</span></li>
                                                <li>
                                                    <span
                                                        >1 Database, 1 Bucket, 2 Functions per
                                                        project</span
                                                    >
                                                </li>
                                            </ul>
                                            <p class="text-caption text-secondary mt-4">
                                                Free projects are paused after 1 week of inactivity.
                                                Limit of 2 projects.
                                            </p>
                                        </div>
                                    </div>
                                </article>
                            </li>
                            <li>
                                <div
                                    class="web-card is-transparent has-border-gradient is-transparent-pink -m-1 h-full p-1! backdrop-blur-none!"
                                    style:--m-border-radius="1.25rem"
                                >
                                    <article
                                        class="web-card is-transparent is-transparent-pink has-border-gradient h-full"
                                        style="background: linear-gradient(180deg, rgba(253, 54, 110, 0.12) 38.59%, rgba(253, 54, 110, 0) 99.04%);"
                                    >
                                        <header class="web-pricing-cards-header">
                                            <header class="flex gap-3">
                                                <h2
                                                    id="pro"
                                                    class="text-label text-primary font-aeonik-pro"
                                                >
                                                    Pro
                                                </h2>
                                                <div class="web-inline-tag is-pink">
                                                    Most popular
                                                </div>
                                            </header>
                                            <div class="mt-4 flex flex-col gap-2">
                                                <span class="-mb-4">From</span>
                                                <div class="flex items-end gap-2">
                                                    <div
                                                        class="text-title font-aeonik-pro text-primary mt-3"
                                                    >
                                                        $25
                                                    </div>
                                                    <div class="mt-1">/month</div>
                                                </div>
                                            </div>
                                            <p class="text-main-body mt-4 h-[5rem] font-medium">
                                                For production applications that need powerful
                                                functionality and resources to scale.
                                            </p>
                                            <Button
                                                href={getAppwriteDashboardUrl(
                                                    '/console?type=create&plan=tier-1'
                                                )}
                                                class="is-full-width mt-11"
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                event="pricing-cards-pro-click"
                                            >
                                                <span class="text-sub-body font-medium"
                                                    >Start building</span
                                                >
                                            </Button>
                                        </header>
                                        <div class="web-pricing-cards-content">
                                            <p>Dedicated resources per project:</p>
                                            <ul class="web-checked-list-circle">
                                                <li><span>2TB bandwidth</span></li>
                                                <li><span>150GB storage</span></li>
                                                <li><span>3.5M executions</span></li>
                                                <li><span>200K monthly active users</span></li>
                                                <li><span>Organization roles</span></li>
                                                <li><span>Email support</span></li>
                                                <li>
                                                    <span>Daily backups stored for 7 days</span>
                                                </li>
                                                <li><span>Add-ons</span></li>
                                                <li>
                                                    <span
                                                        >Unlimited Databases, Buckets, and Functions</span
                                                    >
                                                </li>
                                            </ul>
                                        </div>
                                    </article>
                                </div>
                            </li>
                            {#if SHOW_SCALE_PLAN}
                                <li>
                                    <article
                                        class="web-card is-transparent has-border-gradient h-full"
                                        style="background: linear-gradient(180deg, rgba(255, 255, 255, 0.04) 63.19%, rgba(255, 255, 255, 0.00) 100%);"
                                    >
                                        <div class="web-pricing-cards-item">
                                            <header class="web-pricing-cards-header">
                                                <h2
                                                    id="scale"
                                                    class="text-label text-primary font-aeonik-pro"
                                                >
                                                    Scale
                                                </h2>

                                                <div class="mt-4 flex flex-col gap-2">
                                                    <span class="-mb-4">From</span>
                                                    <div class="flex items-end gap-2">
                                                        <div
                                                            class="text-title font-aeonik-pro text-primary mt-3"
                                                        >
                                                            $599
                                                        </div>
                                                        <div class="mt-1">/month</div>
                                                    </div>
                                                </div>

                                                <p class="text-main-body mt-4 h-[5rem] font-medium">
                                                    For teams that handle more complex and large
                                                    projects and need more control and support.
                                                </p>
                                                <Button
                                                    variant="secondary"
                                                    href={getAppwriteDashboardUrl(
                                                        '/console?type=create&plan=tier-2'
                                                    )}
                                                    event="pricing-cards-scale-click"
                                                    class="is-full-width mt-10"
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                >
                                                    <span class="text-sub-body font-medium"
                                                        >Start building</span
                                                    >
                                                </Button>
                                            </header>
                                            <div class="web-pricing-cards-content">
                                                <p>Everything in Pro, plus:</p>
                                                <ul class="web-checked-list-circle">
                                                    <li><span>Unlimited seats</span></li>
                                                    <li><span>SOC-2</span></li>
                                                    <li><span>BAA</span></li>
                                                    <li><span>Network logs</span></li>
                                                    <li><span>28-day log retention</span></li>
                                                    <li><span>Custom organization roles</span></li>
                                                    <li><span>SSO</span></li>
                                                    <li><span>Activity logs</span></li>
                                                    <li><span>Custom backup policies</span></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </article>
                                </li>
                            {/if}
                            <li>
                                <article
                                    class="web-card is-transparent has-border-gradient u-height-100-percent"
                                    style="background: linear-gradient(180deg, rgba(255, 255, 255, 0.04) 63.19%, rgba(255, 255, 255, 0.00) 100%);"
                                >
                                    <div class="web-pricing-cards-item">
                                        <header class="web-pricing-cards-header">
                                            <h2
                                                id="enterprise"
                                                class="text-label text-primary font-aeonik-pro"
                                            >
                                                Enterprise
                                            </h2>
                                            <div
                                                class="text-title font-aeonik-pro text-primary mt-10 -mb-6"
                                            >
                                                Custom
                                            </div>
                                            <div class="mt-1">&nbsp;</div>
                                            <p class="text-main-body mt-4 h-[5rem] font-medium">
                                                For enterprises that need more power, premium
                                                support, and advanced security features.
                                            </p>
                                            <Button
                                                variant="secondary"
                                                href="/contact-us/enterprise"
                                                class="is-full-width mt-10"
                                                rel="noopener noreferrer"
                                                event="pricing-cards-enterprise-click"
                                            >
                                                <!-- <span class="web-sub-body-500">Start trial</span> -->
                                                <span class="web-sub-body-500">Contact us</span>
                                            </Button>
                                        </header>
                                        <div class="web-pricing-cards-content">
                                            <p>
                                                Everything in {SHOW_SCALE_PLAN ? 'Scale' : 'Pro'},
                                                plus:
                                            </p>
                                            <ul class="web-checked-list-circle">
                                                <li><span>Uptime SLAs</span></li>
                                                <li><span>Designated Success Manager</span></li>
                                                <li><span>Up to 24/7 support</span></li>
                                                <li>
                                                    <span>Option for private Slack channel</span>
                                                </li>
                                                <li><span>Volume discounts</span></li>
                                                <li><span>Log drains</span></li>
                                                <li><span>90-day log retention</span></li>
                                                <li><span>Advanced observability</span></li>
                                                <li><span>Bring your own Cloud</span></li>
                                                <li>
                                                    <span>SOC-2, HIPAA, and BAA</span>
                                                </li>
                                                <li><span>Custom organization roles</span></li>
                                                <li><span>Single Sign-On (SSO)</span></li>
                                                <li><span>Activity logs</span></li>
                                                <li><span>Custom backup policies</span></li>
                                            </ul>
                                        </div>
                                    </div>
                                </article>
                            </li>
                        </ul>
                    </div>

                    <div class="mt-24 grid grid-cols-1 place-items-center gap-4 md:grid-cols-2">
                        <div class="cta-card w-full p-6">
                            <h6
                                class="text-main-body text-primary mb-2 flex items-center gap-3 font-medium"
                            >
                                Enterprises
                            </h6>
                            <p class="text-main-body text-secondary font-medium">
                                Large scale projects seeking greater performance, collaboration and
                                security.
                            </p>
                            <Button
                                class="mt-8"
                                variant="secondary"
                                href="/contact-us"
                                event="pricing-cards-alternate_enterprise-click">Contact us</Button
                            >
                        </div>
                        <div class="cta-card w-full p-6">
                            <h6
                                class="text-main-body text-primary mb-2 flex items-center gap-3 font-medium"
                            >
                                Open Source
                            </h6>
                            <p class="text-main-body text-secondary font-medium">
                                We support open-source teams with free access to {SHOW_SCALE_PLAN
                                    ? 'Pro and Scale'
                                    : 'Pro'} plans.
                            </p>
                            <Button
                                variant="secondary"
                                href="/docs/advanced/platform/oss"
                                event="pricing-cards-oss_learn_more-click"
                                class="mt-8">Learn More</Button
                            >
                        </div>
                    </div>
                </section>
            </div>
        </div>

        <ComparePlans />

        <div class="dark relative overflow-hidden pt-10">
            <div class="web-big-padding-section-level-2 relative">
                <div class="relative container" style:z-index="10">
                    <section class="web-grid-4-6">
                        <header>
                            <div class="text-display font-aeonik-pro text-primary">FAQ</div>
                        </header>
                        <Faq />
                    </section>
                </div>
            </div>
            <div class="web-big-padding-section-level-2 relative !mb-0">
                <div class="container">
                    <PreFooter />
                    <FooterNav />
                    <MainFooter />
                </div>
            </div>
        </div>
    </div>
</Main>

<style lang="scss">
    @use '$scss/abstract/mixins/border-gradient' as gradients;

    .web-card {
        --web-color-border: 240, 4%, 18%;
        --p-card-padding: 1.25rem;
    }
    @media (min-width: 360px) and (max-width: 550px) {
        .web-location-for-mobile {
            inset-block-start: 90px;
        }
    }

    .web-pricing-cards-list {
        gap: 1rem;
        grid-template-columns: var(--columns-template);
    }

    .cta-card {
        @include gradients.border-gradient;
        --p-radius: 16px;

        background-color: hsl(var(--web-color-card));
        border-radius: var(--p-radius);
        --m-border-radius: var(--p-radius);
        --m-border-gradient-before: linear-gradient(
            180deg,
            rgba(255, 255, 255, 0.12) 0%,
            rgba(255, 255, 255, 0) 125.11%
        );
    }
</style>

// clikkle-app/app/pricing/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { SiteFooter } from '@/components/site-footer';
import { PreFooter } from '@/components/pre-footer';
import { withBasePath } from '@/lib/basepath';
import './pricing.css';
import { comparisonTables, faqItems, type CellValue, type LinkRow } from './pricing-data';

/* ─── Feature list check — geometry parity with Appwrite `checked-badge` (20×20, r=8 circle) ─── */
function CheckCircle() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden>
      <circle
        cx="10"
        cy="10"
        r="8"
        fill="rgba(45, 99, 255, 0.08)"
        stroke="#2D63FF"
        strokeOpacity={0.32}
        strokeWidth={1.2}
      />
      <path
        d="M6.25 11.5L8.75 13.5L13.75 7"
        stroke="#E4E4E7"
        strokeWidth={1.2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/* ─── SVG helper: gradient checkmark for comparison table ─── */
function GradientCheck() {
  return (
    <svg className="pricing-check-icon" width="20" height="20" viewBox="0 0 24 24" fill="none">
      <path
        d="M5 13l4 4L19 7"
        stroke="#2D63FF"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/* ─── Info icon for tooltips ─── */
function InfoIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor">
      <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm1 12H7V7h2v5zm0-6H7V4h2v2z" />
    </svg>
  );
}

/* ─── Chevron icon ─── */
function ChevronDown() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M5 7.5L10 12.5L15 7.5" />
    </svg>
  );
}

const CLOUD_REGISTER = 'https://cloud.clikkle.com/register';
const CLOUD_PRO_CREATE = 'https://cloud.clikkle.com/console?type=create&plan=tier-1';

/* ═══════════════════════════════════════════════
   Pricing cards + bottom CTA row — matches src/routes/pricing/+page.svelte
   ═══════════════════════════════════════════════ */
const PRICING_COLUMNS = 'repeat(3, 1fr)';

function PricingCardsGrid() {
  return (
    <>
      {/* Svelte +page.svelte: --columns-template on .web-pricing-cards; list gap 1rem in page <style> */}
      <div
        className="web-pricing-cards pricing-web-pricing-cards"
        style={{ ['--columns-template' as string]: PRICING_COLUMNS }}
      >
        <ul className="web-pricing-cards-list pricing-cards-grid">
            {/* ── Free — article > .web-pricing-cards-item > header + content ── */}
            <li>
              <article className="pricing-card web-card-pricing">
                <div className="pricing-card__item">
                  <header className="web-pricing-cards-header pricing-card__header">
                    <h2 id="starter" className="pricing-card__name">
                      Free
                    </h2>
                    <div className="pricing-card__price-stack pricing-card__price-stack--simple">
                      <div className="pricing-card__price pricing-price">$0</div>
                      <div className="pricing-card__price-spacer" aria-hidden>
                        &nbsp;
                      </div>
                    </div>
                    <p className="pricing-card__desc pricing-description">
                      A great fit for passion projects and small applications.
                    </p>
                    <a
                      href={CLOUD_REGISTER}
                      className="web-btn web-btn-secondary pricing-card__cta is-full-width"
                    >
                      <span className="pricing-card__btn-label">Start building</span>
                    </a>
                  </header>
                  <div className="web-pricing-cards-content pricing-card__content">
                    <ul className="pricing-checked-list web-checked-list-circle">
                      <li>
                        <CheckCircle />
                        <span>5GB bandwidth</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>2GB storage</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>750K executions</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>75K monthly active users</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Community support</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>1 Database, 1 Bucket, 2 Functions per project</span>
                      </li>
                    </ul>
                    <p className="pricing-card__note">
                      Free projects are paused after 1 week of inactivity. Limit of 2 projects.
                    </p>
                  </div>
                </div>
              </article>
            </li>

            {/* ── Pro — outer gradient border; article has header + content only (no inner item) ── */}
            <li>
              <div className="pricing-card-pro-wrapper web-card-pro-outer pricing-card-pro-wrapper--svelte">
                <article className="pricing-card pricing-card--pro web-card-pricing-inner">
                  <header className="web-pricing-cards-header pricing-card__header">
                    {/* Svelte: nested <header class="flex gap-3"> — title + tag inline, not space-between */}
                    <div className="pricing-card-pro-heading-row flex flex-wrap items-center gap-3">
                      <h2 id="pro" className="pricing-card__name">
                        Pro
                      </h2>
                      <span className="pricing-inline-tag web-inline-tag is-pink">Most popular</span>
                    </div>
                    <div className="pricing-card__price-stack">
                      <span className="pricing-card__price-from pricing-card__price-from--tight">
                        From
                      </span>
                      <div className="pricing-card__price-row pricing-card__price-row--pro">
                        <span className="pricing-card__price pricing-price">$25</span>
                        <span className="pricing-card__price-suffix">/month</span>
                      </div>
                    </div>
                    <p className="pricing-card__desc pricing-description">
                      For production applications that need powerful functionality and resources to scale.
                    </p>
                    <a
                      href={CLOUD_PRO_CREATE}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="web-btn web-btn-primary pricing-card__cta is-full-width pricing-card__cta--pro"
                    >
                      <span className="pricing-card__btn-label">Start building</span>
                    </a>
                  </header>
                  <div className="web-pricing-cards-content pricing-card__content">
                    <p className="pricing-card__content-lead">Dedicated resources per project:</p>
                    <ul className="pricing-checked-list web-checked-list-circle">
                      <li>
                        <CheckCircle />
                        <span>2TB bandwidth</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>150GB storage</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>3.5M executions</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>200K monthly active users</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Organization roles</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Email support</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Daily backups stored for 7 days</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Add-ons</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Unlimited Databases, Buckets, and Functions</span>
                      </li>
                    </ul>
                  </div>
                </article>
              </div>
            </li>

            {/* ── Enterprise ── */}
            <li>
              <article className="pricing-card web-card-pricing">
                <div className="pricing-card__item">
                  <header className="web-pricing-cards-header pricing-card__header">
                    <h2 id="enterprise" className="pricing-card__name">
                      Enterprise
                    </h2>
                    <div className="pricing-card__price-stack pricing-card__price-stack--simple">
                      <div className="pricing-card__price pricing-price">Custom</div>
                      <div className="pricing-card__price-spacer" aria-hidden>
                        &nbsp;
                      </div>
                    </div>
                    <p className="pricing-card__desc pricing-description">
                      For enterprises that need more power, premium support, and advanced security features.
                    </p>
                    <Link
                      href="/contact-us/enterprise"
                      className="web-btn web-btn-secondary pricing-card__cta is-full-width pricing-card__cta--enterprise"
                    >
                      <span className="pricing-card__btn-label">Contact us</span>
                    </Link>
                  </header>
                  <div className="web-pricing-cards-content pricing-card__content">
                    <p className="pricing-card__content-lead">Everything in Pro, plus:</p>
                    <ul className="pricing-checked-list web-checked-list-circle">
                      <li>
                        <CheckCircle />
                        <span>Uptime SLAs</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Designated Success Manager</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Up to 24/7 support</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Option for private Slack channel</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Volume discounts</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Log drains</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>90-day log retention</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Advanced observability</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Bring your own Cloud</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>SOC-2, HIPAA, and BAA</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Custom organization roles</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Single Sign-On (SSO)</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Activity logs</span>
                      </li>
                      <li>
                        <CheckCircle />
                        <span>Custom backup policies</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </article>
            </li>
          </ul>
      </div>
    </>
  );
}

/** “One platform. One subscription.” — matches https://appwrite.io/pricing (between tiers and compare). */
function PricingStackSection() {
  return (
    <div className="pricing-stack-section">
      <article className="pricing-stack-card">
        <div className="pricing-stack-intro">
          <h3 className="pricing-stack-title">One platform. One subscription.</h3>
          <div className="pricing-stack-badge">1 vendor • 1 subscription • 1 bill</div>
        </div>
        <p className="pricing-stack-desc">
          Replace fragmented backend, hosting, storage, and delivery tooling with a single platform
          built for the full application lifecycle. Reduce integration surface area, simplify
          procurement, and give your team one system to operate and scale.
        </p>
        <div className="pricing-stack-compare">
          <div className="pricing-state-card">
            <p className="pricing-state-card__label">Before</p>
            <ul className="pricing-state-card__list">
              <li>Multiple tools with overlapping responsibilities</li>
              <li>Separate subscriptions, invoices, and renewal cycles</li>
              <li>More integration, maintenance, and ownership overhead</li>
            </ul>
          </div>
          <div className="pricing-state-card pricing-state-card--after">
            <p className="pricing-state-card__label">After</p>
            <ul className="pricing-state-card__list">
              <li>One platform across the app lifecycle</li>
              <li>One subscription with simpler billing and procurement</li>
              <li>Fewer systems to integrate, secure, and maintain</li>
            </ul>
          </div>
        </div>
        <div className="pricing-stack-footer">
          <a href="#compare-plans" className="pricing-stack-cta">
            See what&apos;s included
          </a>
          <span className="pricing-stack-helper">
            Compare plan limits, included capabilities, and scaling options.
          </span>
        </div>
      </article>
    </div>
  );
}

/* ═══════════════════════════════════════════════
   Compare Plans Table
   ═══════════════════════════════════════════════ */
function CellContent({ value }: { value: CellValue }) {
  if (typeof value === 'boolean' && value) {
    return <GradientCheck />;
  }
  if (typeof value === 'object' && value !== null && 'text' in value) {
    const link = value as LinkRow;
    return <a href={link.url}>{link.text}</a>;
  }
  return <>{String(value)}</>;
}

function ComparePlans() {
  return (
      <div className="web-white-section light py-10 pricing-compare-shell">
      <div className="web-big-padding-section-level-2 pricing-compare-level-2">
        <div className="relative">
          <article className="pricing-compare-article">
          <section className="container pricing-compare-section" id="compare-plans">
        <header className="pricing-compare-header">
          <h3 className="pricing-compare-title">Compare plans</h3>
          <p className="pricing-compare-lead">
            Discover our plans and find the one that fits your project&apos;s needs.
          </p>
        </header>

        {/* Sticky column headers — compare-plans.svelte: Free/Ent secondary, Pro primary */}
        <div className="pricing-compare-sticky">
          <div className="pricing-compare-sticky__label" />
          <div className="pricing-compare-mini-card">
            <h4>Free</h4>
            <a href={CLOUD_REGISTER} className="web-btn web-btn-secondary pricing-compare-mini-btn">
              Start building
            </a>
          </div>
          <div className="pricing-compare-mini-card">
            <h4>Pro</h4>
            <a
              href={CLOUD_PRO_CREATE}
              target="_blank"
              rel="noopener noreferrer"
              className="web-btn web-btn-primary pricing-compare-mini-btn"
            >
              Start building
            </a>
          </div>
          <div className="pricing-compare-mini-card">
            <h4>Enterprise</h4>
            <Link href="/contact-us/enterprise" className="web-btn web-btn-secondary pricing-compare-mini-btn">
              Contact
            </Link>
          </div>
        </div>

        {/* Tables */}
        {comparisonTables.map((table) => (
          <table className="pricing-compare-table" key={table.title}>
            <caption>{table.title}</caption>
            <tbody>
              {table.rows.map((row) => (
                <tr key={row.title}>
                  <th>
                    <div className="info-wrapper">
                      {row.title}
                      {row.info && (
                        <span className="pricing-tooltip-wrapper">
                          <span className="info-icon"><InfoIcon /></span>
                          <span className="pricing-tooltip">{row.info}</span>
                        </span>
                      )}
                    </div>
                  </th>
                  <td><CellContent value={row.free} /></td>
                  <td className="is-pro"><CellContent value={row.pro} /></td>
                  <td><CellContent value={row.enterprise} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        ))}
          </section>
          </article>
        </div>
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════
   FAQ — Svelte: section.web-grid-4-6 inside .container
   ═══════════════════════════════════════════════ */
/** Svelte faq.svelte — list only; parent +page.svelte wraps web-grid-4-6 + FAQ title */
function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number>(0);

  const toggle = (index: number) => {
    setOpenIndex((prev) => (prev === index ? -1 : index));
  };

  return (
    <ul className="pricing-faq-list w-full">
      {faqItems.map((item, index) => (
        <li className="pricing-faq-item" key={index}>
          <button
            className="pricing-faq-trigger"
            type="button"
            onClick={() => toggle(index)}
            aria-expanded={openIndex === index}
          >
            <span>{item.question}</span>
            <span className={`pricing-faq-chevron ${openIndex === index ? 'pricing-faq-chevron--open' : ''}`}>
              <ChevronDown />
            </span>
          </button>
          <div className={`pricing-faq-answer ${openIndex === index ? 'pricing-faq-answer--open' : ''}`}>
            <div
              className="pricing-faq-answer__inner"
              dangerouslySetInnerHTML={{ __html: item.answer }}
            />
          </div>
        </li>
      ))}
    </ul>
  );
}

/* ═══════════════════════════════════════════════
   MAIN PAGE — mirrors src/routes/pricing/+page.svelte layout
   ═══════════════════════════════════════════════ */
export default function PricingPage() {
  return (
    <div className="web-big-padding-section pricing-page-root relative mt-2">
      <div
        className="pricing-bg-decor web-location-for-mobile pointer-events-none absolute w-full overflow-hidden"
        aria-hidden
      >
        <img
          src={withBasePath('/pricing-bg.png')}
          alt=""
          width={1369}
          className="pricing-bg-decor__img"
        />
      </div>

      <div className="dark relative z-[1] pt-8">
        <div className="web-big-padding-section-level-2">
          <section className="container">
            {/*
              src/routes/pricing/+page.svelte:
              text-display font-aeonik-pro web-u-max-width-900 …
              text-description max-w-sm …
            */}
            <div className="web-hero pricing-web-hero">
              <h1 className="pricing-svelte-h1 text-display font-aeonik-pro">
                Pricing
              </h1>
              <p className="pricing-svelte-subtitle text-description max-w-sm">
                Clikkle offers simple and transparent pricing plans with no surprises.
              </p>
            </div>
          </section>
        </div>

        <div className="web-big-padding-section-level-2">
          <section className="container">
            <PricingCardsGrid />
            <PricingStackSection />
          </section>
        </div>
      </div>

      <ComparePlans />

      <div className="dark relative z-[1] overflow-hidden pt-10">
        <div className="web-big-padding-section-level-2 relative">
          <div className="container relative z-10">
            <section className="web-grid-4-6 pricing-faq-grid">
              <header>
                <div className="pricing-faq-title text-display font-aeonik-pro text-primary">FAQ</div>
              </header>
              <FaqSection />
            </section>
          </div>
        </div>
        <div className="web-big-padding-section-level-2 pricing-level-2-footer relative !mb-0">
          <div className="container">
            <PreFooter headingId="pricing-pre-footer-heading" />
            <SiteFooter />
          </div>
        </div>
      </div>
    </div>
  );
}
