// clikkle-app/app/docs/page.tsx
"use client";

import Link from "next/link";
import { useState, useRef } from "react";
import { ChevronLeft, ChevronRight, ArrowRight, Sparkles } from "lucide-react";

/* ─── Data ─── */

const tutorials = [
  {
    href: "/docs/tutorials/react",
    cover: "/clikkle/images/tutorials/react.png",
    title: "React tutorial",
    description: "Learn Clikkle Auth, Databases, and more with React.",
  },
  {
    href: "/docs/tutorials/nextjs",
    cover: "/clikkle/images/tutorials/nextjs.png",
    title: "Next.js tutorial",
    description: "Learn Clikkle Auth, Databases, and more with Next.js.",
  },
  {
    href: "/docs/tutorials/sveltekit",
    cover: "/clikkle/images/tutorials/svelte.png",
    title: "SvelteKit tutorial",
    description: "Learn Clikkle Auth, Databases, and more with SvelteKit.",
  },
  {
    href: "/docs/tutorials/vue",
    cover: "/clikkle/images/tutorials/vue.png",
    title: "Vue tutorial",
    description: "Learn Clikkle Auth, Databases, and more with Vue.",
  },
  {
    href: "/docs/tutorials/android",
    cover: "/clikkle/images/tutorials/android.png",
    title: "Android tutorial",
    description: "Learn Clikkle Auth, Databases, and more with Android.",
  },
  {
    href: "/docs/tutorials/flutter",
    cover: "/clikkle/images/tutorials/flutter.png",
    title: "Flutter tutorial",
    description: "Learn Clikkle Auth, Databases, and more with Flutter.",
  },
];

const capabilities = [
  {
    href: "/docs/products/auth",
    icon: "/clikkle/images/icons/illustrated/dark/auth.png",
    title: "Auth",
    description: "Sign in users with multiple OAuth providers.",
  },
  {
    href: "/docs/products/databases",
    icon: "/clikkle/images/icons/illustrated/dark/databases.png",
    title: "Databases",
    description: "Store your application and user data.",
  },
  {
    href: "/docs/products/functions",
    icon: "/clikkle/images/icons/illustrated/dark/functions.png",
    title: "Functions",
    description: "Extend and customize your server's functionality.",
  },
  {
    href: "/docs/products/sites",
    icon: "/clikkle/images/icons/illustrated/dark/sites.png",
    title: "Sites",
    description: "Deploy websites on the internet at scale.",
  },
  {
    href: "/docs/products/messaging",
    icon: "/clikkle/images/icons/illustrated/dark/messaging.png",
    title: "Messaging",
    description: "Send and schedule email, SMS, and push notifications.",
  },
  {
    href: "/docs/products/storage",
    icon: "/clikkle/images/icons/illustrated/dark/storage.png",
    title: "Storage",
    description: "Store images, videos, documents, and files.",
  },
  {
    href: "/docs/products/avatars",
    icon: "/clikkle/images/icons/illustrated/dark/avatars.png",
    title: "Avatars",
    description: "Generate icons, screenshots, and QR codes for your apps.",
  },
  {
    href: "/docs/apis/realtime",
    icon: "/clikkle/images/icons/illustrated/dark/realtime.png",
    title: "Realtime",
    description: "Respond to server events in realtime.",
  },
];

const mcpTools = [
  {
    href: "/docs/tooling/mcp/claude-desktop",
    icon: "/clikkle/images/docs/mcp/logos/dark/claude.svg",
    title: "Claude Desktop",
  },
  {
    href: "/docs/tooling/mcp/claude-code",
    icon: "/clikkle/images/docs/mcp/logos/dark/claude.svg",
    title: "Claude Code",
  },
  {
    href: "/docs/tooling/mcp/cursor",
    icon: "/clikkle/images/docs/mcp/logos/dark/cursor-ai.svg",
    title: "Cursor",
  },
  {
    href: "/docs/tooling/mcp/windsurf",
    icon: "/clikkle/images/docs/mcp/logos/dark/windsurf.svg",
    title: "Windsurf Editor",
  },
  {
    href: "/docs/tooling/mcp/vscode",
    icon: "/clikkle/images/docs/mcp/logos/dark/vscode.svg",
    title: "VS Code",
  },
  {
    href: "/docs/tooling/mcp/opencode",
    icon: "/clikkle/images/docs/mcp/logos/dark/opencode.svg",
    title: "OpenCode",
  },
];

const integrations = [
  {
    href: "/docs/sdks",
    title: "SDKs",
    description: "Light-weight SDKs for your favorite platforms.",
  },
  {
    href: "/docs/apis/rest",
    title: "REST API",
    description: "Integrate with HTTP requests without needing an SDK.",
  },
  {
    href: "/docs/apis/graphql",
    title: "GraphQL",
    description:
      "Leverage GraphQL through our SDKs or integrate directly with REST endpoints.",
  },
  {
    href: "/docs/apis/realtime",
    title: "Realtime",
    description:
      "Respond to auth, databases, storage, and function events in realtime.",
  },
];

const migrations = [
  {
    href: "/docs/advanced/migrations/self-hosted",
    title: "Self-hosted",
    description: "Move data from self-hosted to Clikkle Cloud.",
  },
  {
    href: "/docs/advanced/migrations/firebase",
    title: "Firebase",
    description: "Migrate users and data from Firebase to Clikkle.",
  },
  {
    href: "/docs/advanced/migrations/supabase",
    title: "Supabase",
    description: "Migrate users and data from Supabase to Clikkle.",
  },
  {
    href: "/docs/advanced/migrations/nhost",
    title: "Nhost",
    description: "Migrate users and data from NHost to Clikkle.",
  },
];

/* Platform icon strip — matching the clikkle.io docs hero */
const platformIcons = [
  "nextjs", "react", "vue", "angular", "svelte", "nuxt",
  "remix", "apple", "android", "kotlin", "swift", "react-native",
  "nodejs", "php", "deno", "dotnet", "go", "python",
];

/* ─── Components ─── */

function DocCard({
  href,
  icon,
  title,
  description,
}: {
  href: string;
  icon?: string;
  title: string;
  description: string;
}) {
  return (
    <Link
      href={href}
      className="group flex flex-col gap-1 rounded-2xl border border-offset bg-card p-5 transition-all hover:bg-smooth"
    >
      {icon ? (
        <img src={icon}
          alt=""
          width={40}
          height={40}
          className="mb-1"
          loading="lazy" />
      ) : null}
      <h4 className="text-[14px] font-medium leading-[1.2] text-primary">{title}</h4>
      <p className="text-[14px] leading-[1.375] text-secondary">{description}</p>
    </Link>
  );
}

function McpCard({
  href,
  icon,
  title,
}: {
  href: string;
  icon: string;
  title: string;
}) {
  return (
    <Link
      href={href}
      className="flex items-center gap-2 rounded-2xl border border-offset bg-card p-5 transition-all hover:bg-smooth"
    >
      <img src={icon} alt="" width={24} height={24} loading="lazy" />
      <h4 className="text-[14px] font-medium leading-[1.2] text-primary">{title}</h4>
    </Link>
  );
}

function TutorialCarousel() {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(true);

  const updateScrollState = () => {
    if (!scrollRef.current) return;
    const el = scrollRef.current;
    setCanScrollLeft(el.scrollLeft > 10);
    setCanScrollRight(el.scrollLeft + el.clientWidth < el.scrollWidth - 10);
  };

  const scroll = (dir: "left" | "right") => {
    if (!scrollRef.current) return;
    const amount = 300;
    scrollRef.current.scrollBy({
      left: dir === "left" ? -amount : amount,
      behavior: "smooth",
    });
  };

  return (
    <div className="relative mt-8">
      {/* Nav arrows */}
      <div className="absolute -top-12 right-0 flex gap-2">
        <button
          onClick={() => scroll("left")}
          disabled={!canScrollLeft}
          className="flex h-8 w-8 items-center justify-center rounded-full border border-offset text-tertiary transition-colors hover:text-primary disabled:opacity-30"
        >
          <ChevronLeft size={16} />
        </button>
        <button
          onClick={() => scroll("right")}
          disabled={!canScrollRight}
          className="flex h-8 w-8 items-center justify-center rounded-full border border-offset text-tertiary transition-colors hover:text-primary disabled:opacity-30"
        >
          <ChevronRight size={16} />
        </button>
      </div>

      <div
        ref={scrollRef}
        onScroll={updateScrollState}
        className="scrollbar-hide flex gap-6 overflow-x-auto scroll-smooth"
        style={{ scrollSnapType: "x mandatory" }}
      >
        {tutorials.map((t) => (
          <Link
            key={t.href}
            href={t.href}
            className="group w-[260px] shrink-0 overflow-hidden rounded-2xl border border-offset bg-card transition-all hover:bg-smooth"
            style={{ scrollSnapAlign: "start" }}
          >
            <div className="aspect-[4/3] overflow-hidden">
              <img src={t.cover}
                alt={t.title}
                className="h-full w-full object-cover transition-transform group-hover:scale-105"
                loading="lazy" />
            </div>
            <div className="p-4">
              <h4 className="text-[14px] font-medium leading-[1.2] text-primary">{t.title}</h4>
              <p className="mt-1 text-[14px] leading-[1.375] text-secondary">{t.description}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

/* ─── Page ─── */

export default function DocsPage() {
  return (
    <main className="web-main-section relative overflow-x-hidden" id="main">
      {/* BGS */}
      <div className="absolute top-0 left-12 -z-10 translate-x-32 md:translate-x-96 opacity-60">
        <img src="/clikkle/images/bgs/docs-blur-1.svg" alt="" className="w-[800px] h-auto max-w-none" loading="lazy" />
      </div>
      <div className="absolute top-4 -left-12 -z-10 opacity-40 md:opacity-60">
        <img src="/clikkle/images/bgs/docs-blur-2.png" alt="" className="w-[600px] h-auto max-w-none" loading="lazy" />
      </div>

      {/* Hero */}
      <section className="relative mt-8 xl:mt-20">
        {/* Announcement badge */}
        <Link
          href="/docs/tooling/mcp"
          className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--color-badge-border)] bg-[var(--color-badge-bg)] px-4 py-1.5 text-sm font-medium text-secondary transition-colors hover:border-[var(--color-brand-primary)]"
        >
          <span className="flex items-center gap-1 text-[#2D63FF]">
            <Sparkles size={14} />
            New
          </span>
          <span>MCP Server</span>
          <ArrowRight size={14} className="text-tertiary" />
        </Link>

        <h1 className="font-aeonik-pro text-[4rem] font-bold leading-none tracking-tight text-primary md:text-[5rem]">
          Docs<span className="text-[#2D63FF]">_</span>
        </h1>
        <p className="mt-6 max-w-[600px] text-lg text-secondary">
          Clikkle helps you build secure and scalable apps, faster. Leverage
          Clikkle&apos;s powerful APIs to stop fighting technologies and start
          delivering value.
        </p>

        <Link
          href="/docs/quick-starts"
          className="mt-8 inline-flex items-center justify-center rounded-lg border border-[#2D63FF] px-6 py-2.5 text-sm font-semibold text-[#2D63FF] transition-colors hover:bg-[#2D63FF] hover:text-white"
        >
          Quickstart guides
        </Link>
      </section>

      {/* Platform Icons Strip */}
      <section className="mt-12 flex flex-wrap gap-4">
        {platformIcons.map((name) => (
          <div
            key={name}
            className="flex h-10 w-10 items-center justify-center rounded-lg border border-[var(--color-border-subtle)] bg-[var(--bg-secondary)] text-tertiary"
          >
            <img src={`/clikkle/images/platforms/dark/${name}.svg`}
              alt={name}
              width={24}
              height={24}
              loading="lazy"
              className="opacity-50"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = "none";
              }}
            />
          </div>
        ))}
      </section>

      {/* Show Me Some Code */}
      <section className="mt-12">
        <h2 className="font-aeonik-pro text-3xl font-bold tracking-tight text-primary md:text-4xl">
          Show me some code
        </h2>
        <p className="mt-4 max-w-[600px] text-secondary">
          If you learn best from code examples, follow one of our tutorials.
        </p>
        <TutorialCarousel />
      </section>

      {/* Explore Capabilities */}
      <section className="mt-12">
        <h2 className="font-aeonik-pro text-3xl font-bold tracking-tight text-primary md:text-4xl">
          Explore capabilities
        </h2>
        <p className="mt-4 max-w-[600px] text-secondary">
          All the core functionalities you need with a scalable and flexible
          API. Explore Clikkle&apos;s product offerings.
        </p>
        <div className="mt-6 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {capabilities.map((c) => (
            <DocCard key={c.title} {...c} />
          ))}
        </div>
      </section>

      {/* Build faster with AI */}
      <section className="mt-12">
        <h2 className="font-aeonik-pro text-3xl font-bold tracking-tight text-primary md:text-4xl">
          Build faster with AI
        </h2>
        <p className="mt-4 max-w-[600px] text-secondary">
          Clikkle&apos;s Model Context Protocol (MCP) server lets LLMs interact
          directly with your Clikkle API.
        </p>
        <div className="mt-6 grid grid-cols-1 gap-5 md:grid-cols-2">
          {mcpTools.map((t) => (
            <McpCard key={t.title} {...t} />
          ))}
        </div>
      </section>

      {/* Explore ways to integrate */}
      <section className="mt-12">
        <h2 className="font-aeonik-pro text-3xl font-bold tracking-tight text-primary md:text-4xl">
          Explore ways to integrate
        </h2>
        <p className="mt-4 max-w-[600px] text-secondary">
          Choose how you integrate with Clikkle. Explore references for the
          Clikkle SDK, REST API, GraphQL API, or Realtime API.
        </p>
        <div className="mt-6 grid grid-cols-1 gap-8 md:grid-cols-2">
          {integrations.map((i) => (
            <DocCard key={i.title} {...i} />
          ))}
        </div>
      </section>

      {/* Migrate to Clikkle */}
      <section className="mt-12 pb-20">
        <h2 className="font-aeonik-pro text-3xl font-bold tracking-tight text-primary md:text-4xl">
          Migrate to Clikkle
        </h2>
        <p className="mt-4 max-w-[600px] text-secondary">
          Own your data with automatic data migrations.
        </p>
        <div className="mt-6 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {migrations.map((m) => (
            <DocCard key={m.title} {...m} />
          ))}
        </div>
      </section>

    </main>
  );
}

// src/routes/docs/+page.svelte
<script lang="ts">
    import { Carousel } from '$lib/components';
    import Technologies from '$lib/components/Technologies.svelte';
    import { Button } from '$lib/components/ui';
    import Docs from '$lib/layouts/Docs.svelte';
    import { DEFAULT_HOST } from '$lib/utils/metadata';
    import { TITLE_SUFFIX } from '$routes/titles';
    import MainFooter from '../../lib/components/MainFooter.svelte';
    import CodeCard, { type CodeCardProps } from './CodeCard.svelte';
    import Sidebar from './Sidebar.svelte';
    import { trackEvent } from '$lib/actions/analytics';
    import Platforms from '$routes/(marketing)/(components)/platforms.svelte';
    import HeroBanner from '$routes/(marketing)/(components)/hero-banner.svelte';

    const title = 'Docs' + TITLE_SUFFIX;
    const description =
        'Learn how to build like a team of hundreds. Get started with Authentication, Databases, Storage, Functions, and Messaging in your preferred framework.';
    const ogImage = DEFAULT_HOST + '/images/open-graph/docs.png';

    const tutorials: CodeCardProps[] = [
        {
            href: '/docs/tutorials/react',
            cover: '/images/tutorials/react.png',
            title: 'React tutorial',
            description: 'Learn Appwrite Auth, Databases, and more with React.'
        },
        {
            href: '/docs/tutorials/nextjs',
            cover: '/images/tutorials/nextjs.png',
            title: 'Next.js tutorial',
            description: 'Learn Appwrite Auth, Databases, and more with Next.js.'
        },
        {
            href: '/docs/tutorials/sveltekit',
            cover: '/images/tutorials/svelte.png',
            title: 'SvelteKit tutorial',
            description: 'Learn Appwrite Auth, Databases, and more with SvelteKit.'
        },
        {
            href: '/docs/tutorials/vue',
            cover: '/images/tutorials/vue.png',
            title: 'Vue tutorial',
            description: 'Learn Appwrite Auth, Databases, and more with Vue.'
        },
        {
            href: '/docs/tutorials/android',
            cover: '/images/tutorials/android.png',
            title: 'Android tutorial',
            description: 'Learn Appwrite Auth, Databases, and more with Android.'
        },
        {
            href: '/docs/tutorials/flutter',
            cover: '/images/tutorials/flutter.png',
            title: 'Flutter tutorial',
            description: 'Learn Appwrite Auth, Databases, and more with Flutter.'
        }
    ];
</script>

<svelte:head>
    <!-- Titles -->
    <title>{title}</title>
    <meta property="og:title" content={title} />
    <meta name="twitter:title" content={title} />
    <!-- Description -->
    <meta name="description" content={description} />
    <meta property="og:description" content={description} />
    <meta name="twitter:description" content={description} />
    <!-- Image -->
    <meta property="og:image" content={ogImage} />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:image" content={ogImage} />
    <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<Docs variant="default">
    <Sidebar />

    <main class="web-main-section relative overflow-x-hidden" id="main">
        <div class="absolute right-0 top-0 max-w-full pointer-events-none opacity-40">
            <img src="/images/bgs/docs-blur-1.svg" alt="" />
        </div>

        <div class="web-u-opacity-40-mobile absolute top-4 left-0">
            <enhanced:img src="./blur-2.png" alt="" />
        </div>

        <section class="web-hero is-align-start e-hero-docs relative">
            <HeroBanner title="MCP Server" href="/docs/tooling/mcp" />
            <h1 class="text-display font-aeonik-pro text-primary max-w-[600px]">
                Docs<span class="web-u-color-text-accent">_ </span>
            </h1>
            <p class="text-description max-w-[600px]">
                Appwrite helps you build secure and scalable apps, faster. Leverage Appwrite's
                powerful APIs to stop fighting technologies and start delivering value.
            </p>

            <Button variant="secondary" href="/docs/quick-starts" class="mt-8"
                >Quickstart guides</Button
            >
        </section>
        <div class="overflow-x-clip w-full">
            <Platforms padded={false} class="mt-12! p-0! max-md:p-0!" />
        </div>
        <section class="mt-12!">
            <h2 class="text-title font-aeonik-pro text-primary max-w-[600px]">Show me some code</h2>
            <p class="text-description mt-4 max-w-[600px]">
                If you learn best from code examples, follow one of our tutorials.
            </p>
            <Carousel size="medium">
                {#each tutorials as tutorial}
                    <li style:scroll-snap-align="start">
                        <CodeCard {...tutorial} />
                    </li>
                {/each}
            </Carousel>
        </section>
        <section class="web-hero is-align-start is-no-max-width mt-12!">
            <h2 class="text-title font-aeonik-pro text-primary max-w-[600px]">
                Explore capabilities
            </h2>
            <p class="text-description max-w-[600px]">
                All the core functionalities you need with a scalable and flexible API. Explore
                Appwrite's product offerings.
            </p>
            <div class="mt-6">
                <ul class="web-grid-row-4 web-grid-row-4-m-1">
                    <li>
                        <a
                            href="/docs/products/auth"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_auth-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/auth.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/auth.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Auth</h4>
                            <p class="text-sub-body mt-1">
                                Sign in users with multiple OAuth providers.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/products/databases"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_databases-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/databases.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/databases.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Databases</h4>
                            <p class="text-sub-body mt-1">Store your application and user data.</p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/products/functions"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_functions-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/functions.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/functions.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Functions</h4>
                            <p class="text-sub-body mt-1">
                                Extend and customize your server's functionality.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/products/sites"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_sites-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/sites.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/sites.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Sites</h4>
                            <p class="text-sub-body mt-1">
                                Deploy websites on the internet at scale.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/products/messaging"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_messaging-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/messaging.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/messaging.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Messaging</h4>
                            <p class="text-sub-body mt-1">
                                Send and schedule email, SMS, and push notifications.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/products/storage"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_storage-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/storage.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/storage.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Storage</h4>
                            <p class="text-sub-body mt-1">
                                Store images, videos, documents, and files.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/products/avatars"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_avatars-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/avatars.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/avatars.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Avatars</h4>
                            <p class="text-sub-body mt-1">
                                Generate icons, screenshots, and QR codes for your apps.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/apis/realtime"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-products_realtime-click`)}
                        >
                            <img
                                src="/images/icons/illustrated/dark/realtime.png"
                                alt=""
                                class="web-u-only-dark e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <img
                                src="/images/icons/illustrated/light/realtime.png"
                                alt=""
                                class="web-u-only-light e-docs-product-icon"
                                width="40"
                                height="40"
                            />
                            <h4 class="text-sub-body text-primary mt-2 font-medium">Realtime</h4>
                            <p class="text-sub-body mt-1">Respond to server events in realtime.</p>
                        </a>
                    </li>
                </ul>
            </div>
        </section>
        <section class="web-hero is-align-start is-no-max-width mt-12!">
            <h2 class="text-title font-aeonik-pro text-primary max-w-[600px]">
                Build faster with AI
            </h2>
            <p class="text-description max-w-[600px]">
                Appwrite’s Model Context Protocol (MCP) server lets LLMs interact directly with your
                Appwrite API.
            </p>
            <div class="mt-6">
                <ul class="grid grid-cols-1 gap-8 md:grid-cols-2">
                    <li>
                        <a
                            href="/docs/tooling/mcp/claude-desktop"
                            class="web-card is-normal flex flex-row! items-center gap-2!"
                            onclick={() => trackEvent(`docs-mcp-click`)}
                        >
                            <img
                                src="/images/docs/mcp/logos/dark/claude.svg"
                                alt="Claude"
                                class="w-6"
                            />
                            <h4 class="text-sub-body text-primary font-medium">Claude Desktop</h4>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/tooling/mcp/claude-code"
                            class="web-card is-normal flex flex-row! items-center gap-2!"
                            onclick={() => trackEvent(`docs-mcp-click`)}
                        >
                            <img
                                src="/images/docs/mcp/logos/dark/claude.svg"
                                alt="Claude"
                                class="w-6"
                            />
                            <h4 class="text-sub-body text-primary font-medium">Claude Code</h4>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/tooling/mcp/cursor"
                            class="web-card is-normal flex flex-row! items-center gap-2!"
                            onclick={() => trackEvent(`docs-mcp-click`)}
                        >
                            <img
                                src="/images/docs/mcp/logos/dark/cursor-ai.svg"
                                alt="Cursor"
                                class="w-6"
                            />
                            <h4 class="text-sub-body text-primary font-medium">Cursor</h4>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/tooling/mcp/windsurf"
                            class="web-card is-normal flex flex-row! items-center gap-2!"
                            onclick={() => trackEvent(`docs-mcp-click`)}
                        >
                            <img
                                src="/images/docs/mcp/logos/dark/windsurf.svg"
                                alt="Windsurf"
                                class="w-6"
                            />
                            <h4 class="text-sub-body text-primary font-medium">Windsurf Editor</h4>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/tooling/mcp/vscode"
                            class="web-card is-normal flex flex-row! items-center gap-2!"
                            onclick={() => trackEvent(`docs-mcp-click`)}
                        >
                            <img
                                src="/images/docs/mcp/logos/dark/vscode.svg"
                                alt="VS Code"
                                class="w-6"
                            />
                            <h4 class="text-sub-body text-primary font-medium">VS Code</h4>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/tooling/mcp/opencode"
                            class="web-card is-normal flex flex-row! items-center gap-2!"
                            onclick={() => trackEvent(`docs-mcp-click`)}
                        >
                            <img
                                src="/images/docs/mcp/logos/dark/opencode.svg"
                                alt="OpenCode"
                                class="w-6"
                            />
                            <h4 class="text-sub-body text-primary font-medium">OpenCode</h4>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/tooling/mcp/antigravity"
                            class="web-card is-normal flex flex-row! items-center gap-2!"
                            onclick={() => trackEvent(`docs-mcp-click`)}
                        >
                            <img
                                src="/images/docs/mcp/logos/dark/google-antigravity.svg"
                                alt="Google Antigravity"
                                class="w-6"
                            />
                            <h4 class="text-sub-body text-primary font-medium">
                                Google Antigravity
                            </h4>
                        </a>
                    </li>
                </ul>
            </div>
        </section>
        <section class="web-hero is-align-start is-no-max-width mt-12!">
            <h2 class="text-title font-aeonik-pro text-primary max-w-[600px]">
                Explore ways to integrate
            </h2>
            <p class="text-description max-w-[600px]">
                Choose how you integrate with Appwrite. Explore references for the Appwrite SDK,
                REST API, GraphQL API, or Realtime API.
            </p>
            <div class="mt-6">
                <ul class="web-grid-row-2">
                    <li>
                        <a
                            href="/docs/sdks"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-explore_sdks-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">SDKs</h4>
                            <p class="text-sub-body mt-1">
                                Light-weight SDKs for your favorite platforms.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/apis/rest"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-explore_rest_apis-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">REST API</h4>
                            <p class="text-sub-body mt-1">
                                Integrate with HTTP requests without needing an SDK.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/apis/graphql"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-explore_graphql_apis-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">GraphQL</h4>
                            <p class="text-sub-body mt-1">
                                Leverage GraphQL through our SDKs or integrate directly with REST
                                endpoints.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/apis/realtime"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-explore_realtime_apis-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">Realtime</h4>
                            <p class="text-sub-body mt-1">
                                Respond to auth, databases, storage, and function events in
                                realtime.
                            </p>
                        </a>
                    </li>
                </ul>
            </div>
        </section>
        <section class="web-hero is-align-start is-no-max-width mt-12!">
            <h2 class="text-title font-aeonik-pro text-primary max-w-[600px]">
                Migrate to Appwrite
            </h2>
            <p class="text-description max-w-[600px]">
                Own your data with automatic data migrations.
            </p>
            <div class="mt-6">
                <ul class="web-grid-row-4">
                    <li>
                        <a
                            href="/docs/advanced/migrations/self-hosted"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-migrations_self_hosted-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">Self-hosted</h4>
                            <p class="text-sub-body mt-1">
                                Move data from self-hosted to Appwrite Cloud.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/advanced/migrations/firebase"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-migrations_firebase-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">Firebase</h4>
                            <p class="text-sub-body mt-1">
                                Migrate users and data from Firebase to Appwrite.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/advanced/migrations/supabase"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-migrations_supabase-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">Supabase</h4>
                            <p class="text-sub-body mt-1">
                                Migrate users and data from Supabase to Appwrite.
                            </p>
                        </a>
                    </li>
                    <li>
                        <a
                            href="/docs/advanced/migrations/nhost"
                            class="web-card is-normal"
                            onclick={() => trackEvent(`docs-migrations_nhost-click`)}
                        >
                            <h4 class="text-sub-body text-primary font-medium">Nhost</h4>
                            <p class="text-sub-body mt-1">
                                Migrate users and data from NHost to Appwrite.
                            </p>
                        </a>
                    </li>
                </ul>
            </div>
        </section>

        <MainFooter variant="docs" />
    </main>
</Docs>

<style lang="scss">
    @use '$scss/abstract/mixins/border-gradient' as gradients;

    .e-docs-product-icon {
        filter: hue-rotate(190deg) saturate(1.4) brightness(1.1);
    }

    .e-hero-docs {
        @media (min-width: 1280px) {
            margin-block-start: 5rem;
        }
    }
    .web-main-section {
        max-inline-size: unset;
        margin-inline: unset;
        @media (min-width: 1280px) {
            padding-inline-start: 3rem; // 48px
        }
    }
</style>
