// clikkle-app/components/appwrite-network/map-nav.tsx
import { cn } from '@/lib/utils';
import { ArrowRight, MapPin, Cloudy, Globe } from 'lucide-react';
import Link from 'next/link';

/**
 * DOM + classes from `src/lib/components/appwrite-network/map-nav.svelte`
 * (Tabs.Root = middle wrapper; outer `gap-4`; List shadow matches `8px` intent — Svelte source typo `8p`).
 */
interface MapNavProps {
    activeSegment: string;
    onValueChange: (value: string) => void;
    theme?: 'light' | 'dark';
}

const navItems = [
    {
        label: 'PoP Locations',
        value: 'pop-locations',
        icon: MapPin,
        href: '/docs/products/network/cdn',
        description: 'Points of presence ensure <50ms ping around the globe.'
    },
    {
        label: 'Edges',
        value: 'edges',
        icon: Cloudy,
        href: '/docs/products/network/edges#list',
        description: 'Edges bring compute closer to users for faster response times.'
    },
    {
        label: 'Regions',
        value: 'regions',
        icon: Globe,
        href: '/docs/products/network/regions#list',
        description: 'Regions offer data residency and redundancy across continents.'
    }
];

export function MapNav({ activeSegment, onValueChange, theme = 'dark' }: MapNavProps) {
    const activeItem = navItems.find((item) => item.value === activeSegment) || navItems[0];

    return (
        <div className="flex w-full flex-col gap-4 text-center">
            <div className="flex w-full flex-col items-center justify-center gap-12 md:mt-9">
                <div
                    className={cn(
                        'border-smooth animate-fade-in relative grid w-full max-w-xl grid-cols-1 place-content-center gap-3 overflow-hidden p-1 px-8 shadow-[0px_4px_8px_rgba(0,0,0,0.04)] md:grid-cols-3 md:rounded-full md:border md:px-1',
                        theme === 'light' ? 'md:bg-white' : 'md:bg-card'
                    )}
                    role="tablist"
                    aria-label="Network map layers"
                >
                    {navItems.map((item, index) => {
                        const Icon = item.icon;
                        const isActive = activeSegment === item.value;
                        return (
                            <button
                                key={item.value}
                                type="button"
                                role="tab"
                                aria-selected={isActive}
                                onClick={() => onValueChange(item.value)}
                                className={cn(
                                    'text-caption animate-enter text-primary bg-smooth border-smooth group flex h-8 cursor-pointer items-center justify-center gap-2 rounded-full border font-medium outline-0 transition-colors hover:border-white/12',
                                    isActive &&
                                        'border-accent/36 bg-accent/4 text-accent',
                                    !isActive && theme === 'light' && 'text-primary'
                                )}
                                style={{ animationDelay: `${index * 75}ms` }}
                            >
                                <Icon
                                    className={cn(
                                        '-ml-2 size-4',
                                        isActive && 'text-accent',
                                        theme === 'light' && !isActive && 'text-[#19191C]'
                                    )}
                                />
                                {item.label}
                            </button>
                        );
                    })}
                </div>
            </div>

            <p
                className={cn(
                    'text-caption text-light-secondary text-sm px-4',
                    theme === 'dark' && 'text-white/70'
                )}
            >
                {activeItem.description}

                <Link
                    className={cn(
                        'text-primary group mt-2 flex items-center justify-center gap-px md:hidden',
                        theme === 'dark' && 'text-white'
                    )}
                    href={activeItem.href}
                >
                    Learn more about {activeItem.label}
                    <ArrowRight className="size-4 -rotate-45 transition-all group-hover:translate-x-px group-hover:-translate-y-px group-hover:opacity-100 group-focus-visible:translate-x-px group-focus-visible:-translate-y-px group-focus-visible:opacity-100 xl:opacity-0" />
                </Link>
            </p>
        </div>
    );
}

// src/lib/components/appwrite-network/map-nav.svelte
<script lang="ts">
    import { Tabs } from 'bits-ui';
    import type { IconType } from '../ui';
    import Icon from '../ui/icon/icon.svelte';
    import { cn } from '$lib/utils/cn';
    import { trackEvent } from '$lib/actions/analytics';

    const {
        onValueChange,
        theme = 'dark'
    }: {
        onValueChange: (value: string) => void;
        theme?: 'light' | 'dark';
    } = $props();

    const navItems = [
        {
            label: 'PoP Locations',
            value: 'pop-locations',
            icon: 'pop-locations',
            href: '/docs/products/network/cdn',
            description: 'Points of presence ensure <50ms ping around the globe.'
        },
        {
            label: 'Edges',
            value: 'edges',
            icon: 'edge',
            href: '/docs/products/network/edges#list',
            description: 'Edges bring compute closer to users for faster response times.'
        },
        {
            label: 'Regions',
            value: 'regions',
            icon: 'regions',
            href: '/docs/products/network/regions#list',
            description: 'Regions offer data residency and redundancy across continents.'
        }
    ] satisfies Array<{
        label: string;
        value: string;
        icon: IconType;
        href: string;
        description: string;
    }>;
    let activeIndex = $state(0);
</script>

<div class="flex flex-col gap-4 text-center">
    <Tabs.Root
        onValueChange={(value) => {
            activeIndex = navItems.findIndex((item) => item.value === value);
            onValueChange(value);
        }}
        value={navItems[0]?.value}
        class="flex flex-col items-center justify-center gap-12 md:mt-9"
    >
        <Tabs.List
            class={cn(
                'border-smooth animate-fade-in relative grid w-full max-w-xl grid-cols-1 place-content-center gap-3 overflow-hidden p-1 px-8 shadow-[0px_4px_8px_rgba(0,0,0,0.04)] md:grid-cols-3 md:rounded-full md:border md:px-1',
                theme === 'light' ? 'md:bg-white' : 'md:bg-card'
            )}
        >
            {#each navItems as { label, icon, value }, index}
                <Tabs.Trigger
                    {value}
                    class={cn(
                        'text-caption animate-enter text-primary bg-smooth border-smooth flex h-8 cursor-pointer items-center justify-center gap-2 rounded-full border font-medium outline-0 transition-colors hover:border-white/12',
                        'group data-[state="active"]:bg-accent/4 data-[state="active"]:border-accent/36 data-[state="active"]:text-accent'
                    )}
                    style="animation-delay:{index * 75}ms;"
                    onclick={() => {
                        trackEvent(
                            `network-map-nav-${value.toLowerCase().replace(' ', '-')}-click`
                        );
                    }}
                >
                    <Icon
                        name={icon}
                        class={cn(
                            '-ml-2',
                            "group-data-[state='active']:text-accent",
                            theme === 'light' ? 'text-[#19191C]' : 'text-inherit'
                        )}
                    />
                    {label}
                </Tabs.Trigger>
            {/each}
        </Tabs.List>
    </Tabs.Root>

    <p class="text-caption text-secondary px-4">
        {navItems[activeIndex].description}

        <a
            class="text-primary group mt-2 flex items-center justify-center gap-0.25 md:hidden"
            href={navItems[activeIndex].href}
            >Learn more about {navItems[activeIndex].label}
            <Icon
                name="arrow-right"
                class="-rotate-45 transition-all group-hover:translate-x-0.25 group-hover:-translate-y-0.25 group-hover:opacity-100 group-focus:translate-x-0.25 group-focus:-translate-y-0.25 group-focus:opacity-100 xl:opacity-0"
            />
        </a>
    </p>
</div>
